// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AutoTag
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "specifications_json")]
        public string SpecificationsJson;
        [DataMember(Name = "remove_tags_automatically")]
        public bool RemoveTagsAutomatically;
        [DataMember(Name = "tags_json")]
        public string TagsJson;

        public AutoTag(
            int Id,
            string Name,
            string SpecificationsJson,
            bool RemoveTagsAutomatically,
            string TagsJson
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.SpecificationsJson = SpecificationsJson;
            this.RemoveTagsAutomatically = RemoveTagsAutomatically;
            this.TagsJson = TagsJson;
        }

        public AutoTag()
        {
            this.Name = "";
            this.SpecificationsJson = "";
            this.TagsJson = "";
        }
    }
}
