// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CommandRow
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "body_json")]
        public string BodyJson;
        [DataMember(Name = "priority")]
        public int Priority;
        [DataMember(Name = "status")]
        public int Status;
        [DataMember(Name = "result")]
        public int Result;
        [DataMember(Name = "queued_at")]
        public SpacetimeDB.Timestamp QueuedAt;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp? StartedAt;
        [DataMember(Name = "ended_at")]
        public SpacetimeDB.Timestamp? EndedAt;
        [DataMember(Name = "duration_ticks")]
        public long? DurationTicks;
        [DataMember(Name = "exception")]
        public string Exception;
        [DataMember(Name = "trigger")]
        public int Trigger;

        public CommandRow(
            int Id,
            string Name,
            string BodyJson,
            int Priority,
            int Status,
            int Result,
            SpacetimeDB.Timestamp QueuedAt,
            SpacetimeDB.Timestamp? StartedAt,
            SpacetimeDB.Timestamp? EndedAt,
            long? DurationTicks,
            string Exception,
            int Trigger
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.BodyJson = BodyJson;
            this.Priority = Priority;
            this.Status = Status;
            this.Result = Result;
            this.QueuedAt = QueuedAt;
            this.StartedAt = StartedAt;
            this.EndedAt = EndedAt;
            this.DurationTicks = DurationTicks;
            this.Exception = Exception;
            this.Trigger = Trigger;
        }

        public CommandRow()
        {
            this.Name = "";
            this.BodyJson = "";
            this.Exception = "";
        }
    }
}
