// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CustomFilter
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "type")]
        public string Type;
        [DataMember(Name = "label")]
        public string Label;
        [DataMember(Name = "filters")]
        public string Filters;

        public CustomFilter(
            int Id,
            string Type,
            string Label,
            string Filters
        )
        {
            this.Id = Id;
            this.Type = Type;
            this.Label = Label;
            this.Filters = Filters;
        }

        public CustomFilter()
        {
            this.Type = "";
            this.Label = "";
            this.Filters = "";
        }
    }
}
