// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DelayProfile
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "enable_usenet")]
        public bool EnableUsenet;
        [DataMember(Name = "enable_torrent")]
        public bool EnableTorrent;
        [DataMember(Name = "preferred_protocol")]
        public int PreferredProtocol;
        [DataMember(Name = "usenet_delay")]
        public int UsenetDelay;
        [DataMember(Name = "torrent_delay")]
        public int TorrentDelay;
        [DataMember(Name = "order")]
        public int Order;
        [DataMember(Name = "bypass_if_highest_quality")]
        public bool BypassIfHighestQuality;
        [DataMember(Name = "bypass_if_above_custom_format_score")]
        public bool BypassIfAboveCustomFormatScore;
        [DataMember(Name = "minimum_custom_format_score")]
        public int MinimumCustomFormatScore;
        [DataMember(Name = "tags_json")]
        public string TagsJson;

        public DelayProfile(
            int Id,
            bool EnableUsenet,
            bool EnableTorrent,
            int PreferredProtocol,
            int UsenetDelay,
            int TorrentDelay,
            int Order,
            bool BypassIfHighestQuality,
            bool BypassIfAboveCustomFormatScore,
            int MinimumCustomFormatScore,
            string TagsJson
        )
        {
            this.Id = Id;
            this.EnableUsenet = EnableUsenet;
            this.EnableTorrent = EnableTorrent;
            this.PreferredProtocol = PreferredProtocol;
            this.UsenetDelay = UsenetDelay;
            this.TorrentDelay = TorrentDelay;
            this.Order = Order;
            this.BypassIfHighestQuality = BypassIfHighestQuality;
            this.BypassIfAboveCustomFormatScore = BypassIfAboveCustomFormatScore;
            this.MinimumCustomFormatScore = MinimumCustomFormatScore;
            this.TagsJson = TagsJson;
        }

        public DelayProfile()
        {
            this.TagsJson = "";
        }
    }
}
