// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DownloadClientStatus
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "provider_id")]
        public int ProviderId;
        [DataMember(Name = "initial_failure")]
        public SpacetimeDB.Timestamp? InitialFailure;
        [DataMember(Name = "most_recent_failure")]
        public SpacetimeDB.Timestamp? MostRecentFailure;
        [DataMember(Name = "escalation_level")]
        public int EscalationLevel;
        [DataMember(Name = "disabled_till")]
        public SpacetimeDB.Timestamp? DisabledTill;

        public DownloadClientStatus(
            int Id,
            int ProviderId,
            SpacetimeDB.Timestamp? InitialFailure,
            SpacetimeDB.Timestamp? MostRecentFailure,
            int EscalationLevel,
            SpacetimeDB.Timestamp? DisabledTill
        )
        {
            this.Id = Id;
            this.ProviderId = ProviderId;
            this.InitialFailure = InitialFailure;
            this.MostRecentFailure = MostRecentFailure;
            this.EscalationLevel = EscalationLevel;
            this.DisabledTill = DisabledTill;
        }

        public DownloadClientStatus()
        {
        }
    }
}
