// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EpisodeHistory
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "episode_id")]
        public int EpisodeId;
        [DataMember(Name = "series_id")]
        public int SeriesId;
        [DataMember(Name = "source_title")]
        public string SourceTitle;
        [DataMember(Name = "quality_json")]
        public string QualityJson;
        [DataMember(Name = "quality_id")]
        public int QualityId;
        [DataMember(Name = "date")]
        public SpacetimeDB.Timestamp Date;
        [DataMember(Name = "event_type")]
        public int EventType;
        [DataMember(Name = "data_json")]
        public string DataJson;
        [DataMember(Name = "languages_json")]
        public string LanguagesJson;
        [DataMember(Name = "download_id")]
        public string DownloadId;

        public EpisodeHistory(
            int Id,
            int EpisodeId,
            int SeriesId,
            string SourceTitle,
            string QualityJson,
            int QualityId,
            SpacetimeDB.Timestamp Date,
            int EventType,
            string DataJson,
            string LanguagesJson,
            string DownloadId
        )
        {
            this.Id = Id;
            this.EpisodeId = EpisodeId;
            this.SeriesId = SeriesId;
            this.SourceTitle = SourceTitle;
            this.QualityJson = QualityJson;
            this.QualityId = QualityId;
            this.Date = Date;
            this.EventType = EventType;
            this.DataJson = DataJson;
            this.LanguagesJson = LanguagesJson;
            this.DownloadId = DownloadId;
        }

        public EpisodeHistory()
        {
            this.SourceTitle = "";
            this.QualityJson = "";
            this.DataJson = "";
            this.LanguagesJson = "";
            this.DownloadId = "";
        }
    }
}
