// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EpisodeFile
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "series_id")]
        public int SeriesId;
        [DataMember(Name = "season_number")]
        public int SeasonNumber;
        [DataMember(Name = "relative_path")]
        public string RelativePath;
        [DataMember(Name = "size")]
        public long Size;
        [DataMember(Name = "date_added")]
        public SpacetimeDB.Timestamp DateAdded;
        [DataMember(Name = "original_file_path")]
        public string OriginalFilePath;
        [DataMember(Name = "scene_name")]
        public string SceneName;
        [DataMember(Name = "release_group")]
        public string ReleaseGroup;
        [DataMember(Name = "release_hash")]
        public string ReleaseHash;
        [DataMember(Name = "quality_json")]
        public string QualityJson;
        [DataMember(Name = "quality_id")]
        public int QualityId;
        [DataMember(Name = "indexer_flags")]
        public int IndexerFlags;
        [DataMember(Name = "media_info_json")]
        public string MediaInfoJson;
        [DataMember(Name = "languages_json")]
        public string LanguagesJson;
        [DataMember(Name = "release_type")]
        public int ReleaseType;

        public EpisodeFile(
            int Id,
            int SeriesId,
            int SeasonNumber,
            string RelativePath,
            long Size,
            SpacetimeDB.Timestamp DateAdded,
            string OriginalFilePath,
            string SceneName,
            string ReleaseGroup,
            string ReleaseHash,
            string QualityJson,
            int QualityId,
            int IndexerFlags,
            string MediaInfoJson,
            string LanguagesJson,
            int ReleaseType
        )
        {
            this.Id = Id;
            this.SeriesId = SeriesId;
            this.SeasonNumber = SeasonNumber;
            this.RelativePath = RelativePath;
            this.Size = Size;
            this.DateAdded = DateAdded;
            this.OriginalFilePath = OriginalFilePath;
            this.SceneName = SceneName;
            this.ReleaseGroup = ReleaseGroup;
            this.ReleaseHash = ReleaseHash;
            this.QualityJson = QualityJson;
            this.QualityId = QualityId;
            this.IndexerFlags = IndexerFlags;
            this.MediaInfoJson = MediaInfoJson;
            this.LanguagesJson = LanguagesJson;
            this.ReleaseType = ReleaseType;
        }

        public EpisodeFile()
        {
            this.RelativePath = "";
            this.OriginalFilePath = "";
            this.SceneName = "";
            this.ReleaseGroup = "";
            this.ReleaseHash = "";
            this.QualityJson = "";
            this.MediaInfoJson = "";
            this.LanguagesJson = "";
        }
    }
}
