// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ImportListItem
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "import_list_id")]
        public int ImportListId;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "year")]
        public int Year;
        [DataMember(Name = "tvdb_id")]
        public int TvdbId;
        [DataMember(Name = "tmdb_id")]
        public int TmdbId;
        [DataMember(Name = "imdb_id")]
        public string ImdbId;
        [DataMember(Name = "mal_id")]
        public int MalId;
        [DataMember(Name = "ani_list_id")]
        public int AniListId;
        [DataMember(Name = "release_date")]
        public SpacetimeDB.Timestamp ReleaseDate;

        public ImportListItem(
            int Id,
            int ImportListId,
            string Title,
            int Year,
            int TvdbId,
            int TmdbId,
            string ImdbId,
            int MalId,
            int AniListId,
            SpacetimeDB.Timestamp ReleaseDate
        )
        {
            this.Id = Id;
            this.ImportListId = ImportListId;
            this.Title = Title;
            this.Year = Year;
            this.TvdbId = TvdbId;
            this.TmdbId = TmdbId;
            this.ImdbId = ImdbId;
            this.MalId = MalId;
            this.AniListId = AniListId;
            this.ReleaseDate = ReleaseDate;
        }

        public ImportListItem()
        {
            this.Title = "";
            this.ImdbId = "";
        }
    }
}
