// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MetadataFile
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "series_id")]
        public int SeriesId;
        [DataMember(Name = "episode_file_id")]
        public int? EpisodeFileId;
        [DataMember(Name = "season_number")]
        public int? SeasonNumber;
        [DataMember(Name = "relative_path")]
        public string RelativePath;
        [DataMember(Name = "added")]
        public SpacetimeDB.Timestamp Added;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;
        [DataMember(Name = "extension")]
        public string Extension;
        [DataMember(Name = "hash")]
        public string Hash;
        [DataMember(Name = "consumer")]
        public string Consumer;
        [DataMember(Name = "type")]
        public int Type;

        public MetadataFile(
            int Id,
            int SeriesId,
            int? EpisodeFileId,
            int? SeasonNumber,
            string RelativePath,
            SpacetimeDB.Timestamp Added,
            SpacetimeDB.Timestamp LastUpdated,
            string Extension,
            string Hash,
            string Consumer,
            int Type
        )
        {
            this.Id = Id;
            this.SeriesId = SeriesId;
            this.EpisodeFileId = EpisodeFileId;
            this.SeasonNumber = SeasonNumber;
            this.RelativePath = RelativePath;
            this.Added = Added;
            this.LastUpdated = LastUpdated;
            this.Extension = Extension;
            this.Hash = Hash;
            this.Consumer = Consumer;
            this.Type = Type;
        }

        public MetadataFile()
        {
            this.RelativePath = "";
            this.Extension = "";
            this.Hash = "";
            this.Consumer = "";
        }
    }
}
