// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MetadataDefinition
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "implementation")]
        public string Implementation;
        [DataMember(Name = "config_contract")]
        public string ConfigContract;
        [DataMember(Name = "settings_json")]
        public string SettingsJson;
        [DataMember(Name = "enable")]
        public bool Enable;
        [DataMember(Name = "tags_json")]
        public string TagsJson;
        [DataMember(Name = "message_json")]
        public string MessageJson;

        public MetadataDefinition(
            int Id,
            string Name,
            string Implementation,
            string ConfigContract,
            string SettingsJson,
            bool Enable,
            string TagsJson,
            string MessageJson
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Implementation = Implementation;
            this.ConfigContract = ConfigContract;
            this.SettingsJson = SettingsJson;
            this.Enable = Enable;
            this.TagsJson = TagsJson;
            this.MessageJson = MessageJson;
        }

        public MetadataDefinition()
        {
            this.Name = "";
            this.Implementation = "";
            this.ConfigContract = "";
            this.SettingsJson = "";
            this.TagsJson = "";
            this.MessageJson = "";
        }
    }
}
