// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModuleAuthConfig
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "issuer")]
        public string Issuer;
        [DataMember(Name = "client_ids_comma_separated")]
        public string ClientIdsCommaSeparated;

        public ModuleAuthConfig(
            int Id,
            string Issuer,
            string ClientIdsCommaSeparated
        )
        {
            this.Id = Id;
            this.Issuer = Issuer;
            this.ClientIdsCommaSeparated = ClientIdsCommaSeparated;
        }

        public ModuleAuthConfig()
        {
            this.Issuer = "";
            this.ClientIdsCommaSeparated = "";
        }
    }
}
