// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QualityDefinition
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "quality_json")]
        public string QualityJson;
        [DataMember(Name = "title")]
        public string Title;

        public QualityDefinition(
            int Id,
            string QualityJson,
            string Title
        )
        {
            this.Id = Id;
            this.QualityJson = QualityJson;
            this.Title = Title;
        }

        public QualityDefinition()
        {
            this.QualityJson = "";
            this.Title = "";
        }
    }
}
