// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QualityProfile
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "upgrade_allowed")]
        public bool UpgradeAllowed;
        [DataMember(Name = "cutoff")]
        public int Cutoff;
        [DataMember(Name = "min_format_score")]
        public int MinFormatScore;
        [DataMember(Name = "cutoff_format_score")]
        public int CutoffFormatScore;
        [DataMember(Name = "min_upgrade_format_score")]
        public int MinUpgradeFormatScore;
        [DataMember(Name = "format_items_json")]
        public string FormatItemsJson;
        [DataMember(Name = "items_json")]
        public string ItemsJson;

        public QualityProfile(
            int Id,
            string Name,
            bool UpgradeAllowed,
            int Cutoff,
            int MinFormatScore,
            int CutoffFormatScore,
            int MinUpgradeFormatScore,
            string FormatItemsJson,
            string ItemsJson
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.UpgradeAllowed = UpgradeAllowed;
            this.Cutoff = Cutoff;
            this.MinFormatScore = MinFormatScore;
            this.CutoffFormatScore = CutoffFormatScore;
            this.MinUpgradeFormatScore = MinUpgradeFormatScore;
            this.FormatItemsJson = FormatItemsJson;
            this.ItemsJson = ItemsJson;
        }

        public QualityProfile()
        {
            this.Name = "";
            this.FormatItemsJson = "";
            this.ItemsJson = "";
        }
    }
}
