// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QualityProfileQualityRank
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "profile_id")]
        public int ProfileId;
        [DataMember(Name = "quality_id")]
        public int QualityId;
        [DataMember(Name = "score")]
        public double Score;

        public QualityProfileQualityRank(
            int Id,
            int ProfileId,
            int QualityId,
            double Score
        )
        {
            this.Id = Id;
            this.ProfileId = ProfileId;
            this.QualityId = QualityId;
            this.Score = Score;
        }

        public QualityProfileQualityRank()
        {
        }
    }
}
