// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QualityRankInput
    {
        [DataMember(Name = "quality_id")]
        public int QualityId;
        [DataMember(Name = "score")]
        public double Score;

        public QualityRankInput(
            int QualityId,
            double Score
        )
        {
            this.QualityId = QualityId;
            this.Score = Score;
        }

        public QualityRankInput()
        {
        }
    }
}
