// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RemotePathMapping
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "host")]
        public string Host;
        [DataMember(Name = "remote_path")]
        public string RemotePath;
        [DataMember(Name = "local_path")]
        public string LocalPath;

        public RemotePathMapping(
            int Id,
            string Host,
            string RemotePath,
            string LocalPath
        )
        {
            this.Id = Id;
            this.Host = Host;
            this.RemotePath = RemotePath;
            this.LocalPath = LocalPath;
        }

        public RemotePathMapping()
        {
            this.Host = "";
            this.RemotePath = "";
            this.LocalPath = "";
        }
    }
}
