// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SceneMapping
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "mapping_id")]
        public string MappingId;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "parse_term")]
        public string ParseTerm;
        [DataMember(Name = "search_term")]
        public string SearchTerm;
        [DataMember(Name = "tvdb_id")]
        public int TvdbId;
        [DataMember(Name = "season_number")]
        public int? SeasonNumber;
        [DataMember(Name = "scene_season_number")]
        public int? SceneSeasonNumber;
        [DataMember(Name = "scene_origin")]
        public string SceneOrigin;
        [DataMember(Name = "search_mode")]
        public int? SearchMode;
        [DataMember(Name = "comment")]
        public string Comment;
        [DataMember(Name = "filter_regex")]
        public string FilterRegex;
        [DataMember(Name = "type")]
        public string Type;

        public SceneMapping(
            int Id,
            string MappingId,
            string Title,
            string ParseTerm,
            string SearchTerm,
            int TvdbId,
            int? SeasonNumber,
            int? SceneSeasonNumber,
            string SceneOrigin,
            int? SearchMode,
            string Comment,
            string FilterRegex,
            string Type
        )
        {
            this.Id = Id;
            this.MappingId = MappingId;
            this.Title = Title;
            this.ParseTerm = ParseTerm;
            this.SearchTerm = SearchTerm;
            this.TvdbId = TvdbId;
            this.SeasonNumber = SeasonNumber;
            this.SceneSeasonNumber = SceneSeasonNumber;
            this.SceneOrigin = SceneOrigin;
            this.SearchMode = SearchMode;
            this.Comment = Comment;
            this.FilterRegex = FilterRegex;
            this.Type = Type;
        }

        public SceneMapping()
        {
            this.MappingId = "";
            this.Title = "";
            this.ParseTerm = "";
            this.SearchTerm = "";
            this.SceneOrigin = "";
            this.Comment = "";
            this.FilterRegex = "";
            this.Type = "";
        }
    }
}
