// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScheduledTask
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "type_name")]
        public string TypeName;
        [DataMember(Name = "interval")]
        public int Interval;
        [DataMember(Name = "last_execution")]
        public SpacetimeDB.Timestamp LastExecution;
        [DataMember(Name = "priority")]
        public int Priority;
        [DataMember(Name = "last_start_time")]
        public SpacetimeDB.Timestamp LastStartTime;

        public ScheduledTask(
            int Id,
            string TypeName,
            int Interval,
            SpacetimeDB.Timestamp LastExecution,
            int Priority,
            SpacetimeDB.Timestamp LastStartTime
        )
        {
            this.Id = Id;
            this.TypeName = TypeName;
            this.Interval = Interval;
            this.LastExecution = LastExecution;
            this.Priority = Priority;
            this.LastStartTime = LastStartTime;
        }

        public ScheduledTask()
        {
            this.TypeName = "";
        }
    }
}
