// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SeriesTag
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "series_id")]
        public int SeriesId;
        [DataMember(Name = "tag_id")]
        public int TagId;

        public SeriesTag(
            int Id,
            int SeriesId,
            int TagId
        )
        {
            this.Id = Id;
            this.SeriesId = SeriesId;
            this.TagId = TagId;
        }

        public SeriesTag()
        {
        }
    }
}
