// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Series
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "tvdb_id")]
        public int TvdbId;
        [DataMember(Name = "tv_rage_id")]
        public int TvRageId;
        [DataMember(Name = "tv_maze_id")]
        public int TvMazeId;
        [DataMember(Name = "imdb_id")]
        public string ImdbId;
        [DataMember(Name = "tmdb_id")]
        public int TmdbId;
        [DataMember(Name = "mal_ids_json")]
        public string MalIdsJson;
        [DataMember(Name = "ani_list_ids_json")]
        public string AniListIdsJson;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "clean_title")]
        public string CleanTitle;
        [DataMember(Name = "sort_title")]
        public string SortTitle;
        [DataMember(Name = "status")]
        public int Status;
        [DataMember(Name = "overview")]
        public string Overview;
        [DataMember(Name = "air_time")]
        public string AirTime;
        [DataMember(Name = "monitored")]
        public bool Monitored;
        [DataMember(Name = "monitor_new_items")]
        public int MonitorNewItems;
        [DataMember(Name = "quality_profile_id")]
        public int QualityProfileId;
        [DataMember(Name = "season_folder")]
        public bool SeasonFolder;
        [DataMember(Name = "last_info_sync")]
        public SpacetimeDB.Timestamp? LastInfoSync;
        [DataMember(Name = "runtime")]
        public int Runtime;
        [DataMember(Name = "images_json")]
        public string ImagesJson;
        [DataMember(Name = "series_type")]
        public int SeriesType;
        [DataMember(Name = "network")]
        public string Network;
        [DataMember(Name = "use_scene_numbering")]
        public bool UseSceneNumbering;
        [DataMember(Name = "title_slug")]
        public string TitleSlug;
        [DataMember(Name = "path")]
        public string Path;
        [DataMember(Name = "year")]
        public int Year;
        [DataMember(Name = "ratings_json")]
        public string RatingsJson;
        [DataMember(Name = "genres_json")]
        public string GenresJson;
        [DataMember(Name = "actors_json")]
        public string ActorsJson;
        [DataMember(Name = "certification")]
        public string Certification;
        [DataMember(Name = "added")]
        public SpacetimeDB.Timestamp Added;
        [DataMember(Name = "first_aired")]
        public SpacetimeDB.Timestamp? FirstAired;
        [DataMember(Name = "last_aired")]
        public SpacetimeDB.Timestamp? LastAired;
        [DataMember(Name = "original_language_json")]
        public string OriginalLanguageJson;
        [DataMember(Name = "original_country")]
        public string OriginalCountry;
        [DataMember(Name = "seasons_json")]
        public string SeasonsJson;
        [DataMember(Name = "add_options_json")]
        public string AddOptionsJson;

        public Series(
            int Id,
            int TvdbId,
            int TvRageId,
            int TvMazeId,
            string ImdbId,
            int TmdbId,
            string MalIdsJson,
            string AniListIdsJson,
            string Title,
            string CleanTitle,
            string SortTitle,
            int Status,
            string Overview,
            string AirTime,
            bool Monitored,
            int MonitorNewItems,
            int QualityProfileId,
            bool SeasonFolder,
            SpacetimeDB.Timestamp? LastInfoSync,
            int Runtime,
            string ImagesJson,
            int SeriesType,
            string Network,
            bool UseSceneNumbering,
            string TitleSlug,
            string Path,
            int Year,
            string RatingsJson,
            string GenresJson,
            string ActorsJson,
            string Certification,
            SpacetimeDB.Timestamp Added,
            SpacetimeDB.Timestamp? FirstAired,
            SpacetimeDB.Timestamp? LastAired,
            string OriginalLanguageJson,
            string OriginalCountry,
            string SeasonsJson,
            string AddOptionsJson
        )
        {
            this.Id = Id;
            this.TvdbId = TvdbId;
            this.TvRageId = TvRageId;
            this.TvMazeId = TvMazeId;
            this.ImdbId = ImdbId;
            this.TmdbId = TmdbId;
            this.MalIdsJson = MalIdsJson;
            this.AniListIdsJson = AniListIdsJson;
            this.Title = Title;
            this.CleanTitle = CleanTitle;
            this.SortTitle = SortTitle;
            this.Status = Status;
            this.Overview = Overview;
            this.AirTime = AirTime;
            this.Monitored = Monitored;
            this.MonitorNewItems = MonitorNewItems;
            this.QualityProfileId = QualityProfileId;
            this.SeasonFolder = SeasonFolder;
            this.LastInfoSync = LastInfoSync;
            this.Runtime = Runtime;
            this.ImagesJson = ImagesJson;
            this.SeriesType = SeriesType;
            this.Network = Network;
            this.UseSceneNumbering = UseSceneNumbering;
            this.TitleSlug = TitleSlug;
            this.Path = Path;
            this.Year = Year;
            this.RatingsJson = RatingsJson;
            this.GenresJson = GenresJson;
            this.ActorsJson = ActorsJson;
            this.Certification = Certification;
            this.Added = Added;
            this.FirstAired = FirstAired;
            this.LastAired = LastAired;
            this.OriginalLanguageJson = OriginalLanguageJson;
            this.OriginalCountry = OriginalCountry;
            this.SeasonsJson = SeasonsJson;
            this.AddOptionsJson = AddOptionsJson;
        }

        public Series()
        {
            this.ImdbId = "";
            this.MalIdsJson = "";
            this.AniListIdsJson = "";
            this.Title = "";
            this.CleanTitle = "";
            this.SortTitle = "";
            this.Overview = "";
            this.AirTime = "";
            this.ImagesJson = "";
            this.Network = "";
            this.TitleSlug = "";
            this.Path = "";
            this.RatingsJson = "";
            this.GenresJson = "";
            this.ActorsJson = "";
            this.Certification = "";
            this.OriginalLanguageJson = "";
            this.OriginalCountry = "";
            this.SeasonsJson = "";
            this.AddOptionsJson = "";
        }
    }
}
