// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SubtitleFile
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "series_id")]
        public int SeriesId;
        [DataMember(Name = "episode_file_id")]
        public int? EpisodeFileId;
        [DataMember(Name = "season_number")]
        public int? SeasonNumber;
        [DataMember(Name = "relative_path")]
        public string RelativePath;
        [DataMember(Name = "added")]
        public SpacetimeDB.Timestamp Added;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;
        [DataMember(Name = "extension")]
        public string Extension;
        [DataMember(Name = "language_json")]
        public string LanguageJson;
        [DataMember(Name = "copy")]
        public int Copy;
        [DataMember(Name = "language_tags_json")]
        public string LanguageTagsJson;
        [DataMember(Name = "title")]
        public string Title;

        public SubtitleFile(
            int Id,
            int SeriesId,
            int? EpisodeFileId,
            int? SeasonNumber,
            string RelativePath,
            SpacetimeDB.Timestamp Added,
            SpacetimeDB.Timestamp LastUpdated,
            string Extension,
            string LanguageJson,
            int Copy,
            string LanguageTagsJson,
            string Title
        )
        {
            this.Id = Id;
            this.SeriesId = SeriesId;
            this.EpisodeFileId = EpisodeFileId;
            this.SeasonNumber = SeasonNumber;
            this.RelativePath = RelativePath;
            this.Added = Added;
            this.LastUpdated = LastUpdated;
            this.Extension = Extension;
            this.LanguageJson = LanguageJson;
            this.Copy = Copy;
            this.LanguageTagsJson = LanguageTagsJson;
            this.Title = Title;
        }

        public SubtitleFile()
        {
            this.RelativePath = "";
            this.Extension = "";
            this.LanguageJson = "";
            this.LanguageTagsJson = "";
            this.Title = "";
        }
    }
}
