// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tag
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "label")]
        public string Label;

        public Tag(
            int Id,
            string Label
        )
        {
            this.Id = Id;
            this.Label = Label;
        }

        public Tag()
        {
            this.Label = "";
        }
    }
}
