// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TrustedConnection
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "subject")]
        public string Subject;
        [DataMember(Name = "issuer")]
        public string Issuer;
        [DataMember(Name = "connected_at")]
        public SpacetimeDB.Timestamp ConnectedAt;

        public TrustedConnection(
            SpacetimeDB.Identity Identity,
            string Subject,
            string Issuer,
            SpacetimeDB.Timestamp ConnectedAt
        )
        {
            this.Identity = Identity;
            this.Subject = Subject;
            this.Issuer = Issuer;
            this.ConnectedAt = ConnectedAt;
        }

        public TrustedConnection()
        {
            this.Subject = "";
            this.Issuer = "";
        }
    }
}
