// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UpdateHistory
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "date")]
        public SpacetimeDB.Timestamp Date;
        [DataMember(Name = "version")]
        public string Version;
        [DataMember(Name = "event_type")]
        public int EventType;

        public UpdateHistory(
            int Id,
            SpacetimeDB.Timestamp Date,
            string Version,
            int EventType
        )
        {
            this.Id = Id;
            this.Date = Date;
            this.Version = Version;
            this.EventType = EventType;
        }

        public UpdateHistory()
        {
            this.Version = "";
        }
    }
}
