// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BlocklistHandle : RemoteTableHandle<EventContext, Blocklist>
        {
            public override string RemoteTableName => "blocklist";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Blocklist row) => row.Id;

                public IdUniqueIndex(BlocklistHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BlocklistHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Blocklist row) => row.Id;
        }

        public readonly BlocklistHandle Blocklist;
    }

    public sealed class BlocklistCols
    {
        public global::SpacetimeDB.Col<Blocklist, int> Id { get; }
        public global::SpacetimeDB.Col<Blocklist, int> SeriesId { get; }
        public global::SpacetimeDB.Col<Blocklist, string> EpisodeIdsJson { get; }
        public global::SpacetimeDB.Col<Blocklist, string> SourceTitle { get; }
        public global::SpacetimeDB.Col<Blocklist, string> QualityJson { get; }
        public global::SpacetimeDB.Col<Blocklist, int> QualityId { get; }
        public global::SpacetimeDB.Col<Blocklist, SpacetimeDB.Timestamp> Date { get; }
        public global::SpacetimeDB.Col<Blocklist, SpacetimeDB.Timestamp> PublishedDate { get; }
        public global::SpacetimeDB.Col<Blocklist, long> Size { get; }
        public global::SpacetimeDB.Col<Blocklist, int> Protocol { get; }
        public global::SpacetimeDB.Col<Blocklist, string> Indexer { get; }
        public global::SpacetimeDB.Col<Blocklist, int> IndexerFlags { get; }
        public global::SpacetimeDB.Col<Blocklist, int> ReleaseType { get; }
        public global::SpacetimeDB.Col<Blocklist, string> Message { get; }
        public global::SpacetimeDB.Col<Blocklist, string> Source { get; }
        public global::SpacetimeDB.Col<Blocklist, string> TorrentInfoHash { get; }
        public global::SpacetimeDB.Col<Blocklist, string> LanguagesJson { get; }

        public BlocklistCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "series_id");
            EpisodeIdsJson = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "episode_ids_json");
            SourceTitle = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "source_title");
            QualityJson = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "quality_json");
            QualityId = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "quality_id");
            Date = new global::SpacetimeDB.Col<Blocklist, SpacetimeDB.Timestamp>(tableName, "date");
            PublishedDate = new global::SpacetimeDB.Col<Blocklist, SpacetimeDB.Timestamp>(tableName, "published_date");
            Size = new global::SpacetimeDB.Col<Blocklist, long>(tableName, "size");
            Protocol = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "protocol");
            Indexer = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "indexer");
            IndexerFlags = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "indexer_flags");
            ReleaseType = new global::SpacetimeDB.Col<Blocklist, int>(tableName, "release_type");
            Message = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "message");
            Source = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "source");
            TorrentInfoHash = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "torrent_info_hash");
            LanguagesJson = new global::SpacetimeDB.Col<Blocklist, string>(tableName, "languages_json");
        }
    }

    public sealed class BlocklistIxCols
    {
        public global::SpacetimeDB.IxCol<Blocklist, int> Id { get; }

        public BlocklistIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Blocklist, int>(tableName, "id");
        }
    }
}
