// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConfigHandle : RemoteTableHandle<EventContext, Config>
        {
            public override string RemoteTableName => "config";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Config row) => row.Id;

                public IdUniqueIndex(ConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Config row) => row.Id;
        }

        public readonly ConfigHandle Config;
    }

    public sealed class ConfigCols
    {
        public global::SpacetimeDB.Col<Config, int> Id { get; }
        public global::SpacetimeDB.Col<Config, string> Key { get; }
        public global::SpacetimeDB.Col<Config, string> Value { get; }

        public ConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Config, int>(tableName, "id");
            Key = new global::SpacetimeDB.Col<Config, string>(tableName, "key");
            Value = new global::SpacetimeDB.Col<Config, string>(tableName, "value");
        }
    }

    public sealed class ConfigIxCols
    {
        public global::SpacetimeDB.IxCol<Config, int> Id { get; }

        public ConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Config, int>(tableName, "id");
        }
    }
}
