// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CustomFormatHandle : RemoteTableHandle<EventContext, CustomFormat>
        {
            public override string RemoteTableName => "custom_format";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CustomFormat row) => row.Id;

                public IdUniqueIndex(CustomFormatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CustomFormatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CustomFormat row) => row.Id;
        }

        public readonly CustomFormatHandle CustomFormat;
    }

    public sealed class CustomFormatCols
    {
        public global::SpacetimeDB.Col<CustomFormat, int> Id { get; }
        public global::SpacetimeDB.Col<CustomFormat, string> Name { get; }
        public global::SpacetimeDB.Col<CustomFormat, bool> IncludeCustomFormatWhenRenaming { get; }
        public global::SpacetimeDB.Col<CustomFormat, string> SpecificationsJson { get; }

        public CustomFormatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CustomFormat, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<CustomFormat, string>(tableName, "name");
            IncludeCustomFormatWhenRenaming = new global::SpacetimeDB.Col<CustomFormat, bool>(tableName, "include_custom_format_when_renaming");
            SpecificationsJson = new global::SpacetimeDB.Col<CustomFormat, string>(tableName, "specifications_json");
        }
    }

    public sealed class CustomFormatIxCols
    {
        public global::SpacetimeDB.IxCol<CustomFormat, int> Id { get; }

        public CustomFormatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CustomFormat, int>(tableName, "id");
        }
    }
}
