// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DelayProfileHandle : RemoteTableHandle<EventContext, DelayProfile>
        {
            public override string RemoteTableName => "delay_profile";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(DelayProfile row) => row.Id;

                public IdUniqueIndex(DelayProfileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DelayProfileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DelayProfile row) => row.Id;
        }

        public readonly DelayProfileHandle DelayProfile;
    }

    public sealed class DelayProfileCols
    {
        public global::SpacetimeDB.Col<DelayProfile, int> Id { get; }
        public global::SpacetimeDB.Col<DelayProfile, bool> EnableUsenet { get; }
        public global::SpacetimeDB.Col<DelayProfile, bool> EnableTorrent { get; }
        public global::SpacetimeDB.Col<DelayProfile, int> PreferredProtocol { get; }
        public global::SpacetimeDB.Col<DelayProfile, int> UsenetDelay { get; }
        public global::SpacetimeDB.Col<DelayProfile, int> TorrentDelay { get; }
        public global::SpacetimeDB.Col<DelayProfile, int> Order { get; }
        public global::SpacetimeDB.Col<DelayProfile, bool> BypassIfHighestQuality { get; }
        public global::SpacetimeDB.Col<DelayProfile, bool> BypassIfAboveCustomFormatScore { get; }
        public global::SpacetimeDB.Col<DelayProfile, int> MinimumCustomFormatScore { get; }
        public global::SpacetimeDB.Col<DelayProfile, string> TagsJson { get; }

        public DelayProfileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "id");
            EnableUsenet = new global::SpacetimeDB.Col<DelayProfile, bool>(tableName, "enable_usenet");
            EnableTorrent = new global::SpacetimeDB.Col<DelayProfile, bool>(tableName, "enable_torrent");
            PreferredProtocol = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "preferred_protocol");
            UsenetDelay = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "usenet_delay");
            TorrentDelay = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "torrent_delay");
            Order = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "order");
            BypassIfHighestQuality = new global::SpacetimeDB.Col<DelayProfile, bool>(tableName, "bypass_if_highest_quality");
            BypassIfAboveCustomFormatScore = new global::SpacetimeDB.Col<DelayProfile, bool>(tableName, "bypass_if_above_custom_format_score");
            MinimumCustomFormatScore = new global::SpacetimeDB.Col<DelayProfile, int>(tableName, "minimum_custom_format_score");
            TagsJson = new global::SpacetimeDB.Col<DelayProfile, string>(tableName, "tags_json");
        }
    }

    public sealed class DelayProfileIxCols
    {
        public global::SpacetimeDB.IxCol<DelayProfile, int> Id { get; }

        public DelayProfileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DelayProfile, int>(tableName, "id");
        }
    }
}
