// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DownloadClientDefinitionHandle : RemoteTableHandle<EventContext, DownloadClientDefinition>
        {
            public override string RemoteTableName => "download_client_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(DownloadClientDefinition row) => row.Id;

                public IdUniqueIndex(DownloadClientDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DownloadClientDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DownloadClientDefinition row) => row.Id;
        }

        public readonly DownloadClientDefinitionHandle DownloadClientDefinition;
    }

    public sealed class DownloadClientDefinitionCols
    {
        public global::SpacetimeDB.Col<DownloadClientDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> Implementation { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> ConfigContract { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> SettingsJson { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, bool> Enable { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> TagsJson { get; }
        public global::SpacetimeDB.Col<DownloadClientDefinition, string> MessageJson { get; }

        public DownloadClientDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DownloadClientDefinition, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "name");
            Implementation = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "implementation");
            ConfigContract = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "config_contract");
            SettingsJson = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "settings_json");
            Enable = new global::SpacetimeDB.Col<DownloadClientDefinition, bool>(tableName, "enable");
            TagsJson = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "tags_json");
            MessageJson = new global::SpacetimeDB.Col<DownloadClientDefinition, string>(tableName, "message_json");
        }
    }

    public sealed class DownloadClientDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<DownloadClientDefinition, int> Id { get; }

        public DownloadClientDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DownloadClientDefinition, int>(tableName, "id");
        }
    }
}
