// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DownloadHistoryHandle : RemoteTableHandle<EventContext, DownloadHistory>
        {
            public override string RemoteTableName => "download_history";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(DownloadHistory row) => row.Id;

                public IdUniqueIndex(DownloadHistoryHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DownloadHistoryHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DownloadHistory row) => row.Id;
        }

        public readonly DownloadHistoryHandle DownloadHistory;
    }

    public sealed class DownloadHistoryCols
    {
        public global::SpacetimeDB.Col<DownloadHistory, int> Id { get; }
        public global::SpacetimeDB.Col<DownloadHistory, int> EventType { get; }
        public global::SpacetimeDB.Col<DownloadHistory, int> SeriesId { get; }
        public global::SpacetimeDB.Col<DownloadHistory, string> DownloadId { get; }
        public global::SpacetimeDB.Col<DownloadHistory, string> SourceTitle { get; }
        public global::SpacetimeDB.Col<DownloadHistory, SpacetimeDB.Timestamp> Date { get; }
        public global::SpacetimeDB.Col<DownloadHistory, int> Protocol { get; }
        public global::SpacetimeDB.Col<DownloadHistory, int> IndexerId { get; }
        public global::SpacetimeDB.Col<DownloadHistory, int> DownloadClientId { get; }
        public global::SpacetimeDB.Col<DownloadHistory, string> ReleaseJson { get; }
        public global::SpacetimeDB.Col<DownloadHistory, string> DataJson { get; }

        public DownloadHistoryCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "id");
            EventType = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "event_type");
            SeriesId = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "series_id");
            DownloadId = new global::SpacetimeDB.Col<DownloadHistory, string>(tableName, "download_id");
            SourceTitle = new global::SpacetimeDB.Col<DownloadHistory, string>(tableName, "source_title");
            Date = new global::SpacetimeDB.Col<DownloadHistory, SpacetimeDB.Timestamp>(tableName, "date");
            Protocol = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "protocol");
            IndexerId = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "indexer_id");
            DownloadClientId = new global::SpacetimeDB.Col<DownloadHistory, int>(tableName, "download_client_id");
            ReleaseJson = new global::SpacetimeDB.Col<DownloadHistory, string>(tableName, "release_json");
            DataJson = new global::SpacetimeDB.Col<DownloadHistory, string>(tableName, "data_json");
        }
    }

    public sealed class DownloadHistoryIxCols
    {
        public global::SpacetimeDB.IxCol<DownloadHistory, int> Id { get; }

        public DownloadHistoryIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DownloadHistory, int>(tableName, "id");
        }
    }
}
