// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DownloadClientStatusHandle : RemoteTableHandle<EventContext, DownloadClientStatus>
        {
            public override string RemoteTableName => "download_client_status";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(DownloadClientStatus row) => row.Id;

                public IdUniqueIndex(DownloadClientStatusHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DownloadClientStatusHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DownloadClientStatus row) => row.Id;
        }

        public readonly DownloadClientStatusHandle DownloadClientStatus;
    }

    public sealed class DownloadClientStatusCols
    {
        public global::SpacetimeDB.Col<DownloadClientStatus, int> Id { get; }
        public global::SpacetimeDB.Col<DownloadClientStatus, int> ProviderId { get; }
        public global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp> InitialFailure { get; }
        public global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp> MostRecentFailure { get; }
        public global::SpacetimeDB.Col<DownloadClientStatus, int> EscalationLevel { get; }
        public global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp> DisabledTill { get; }

        public DownloadClientStatusCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DownloadClientStatus, int>(tableName, "id");
            ProviderId = new global::SpacetimeDB.Col<DownloadClientStatus, int>(tableName, "provider_id");
            InitialFailure = new global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp>(tableName, "initial_failure");
            MostRecentFailure = new global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp>(tableName, "most_recent_failure");
            EscalationLevel = new global::SpacetimeDB.Col<DownloadClientStatus, int>(tableName, "escalation_level");
            DisabledTill = new global::SpacetimeDB.Col<DownloadClientStatus, SpacetimeDB.Timestamp>(tableName, "disabled_till");
        }
    }

    public sealed class DownloadClientStatusIxCols
    {
        public global::SpacetimeDB.IxCol<DownloadClientStatus, int> Id { get; }

        public DownloadClientStatusIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DownloadClientStatus, int>(tableName, "id");
        }
    }
}
