// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EpisodeHandle : RemoteTableHandle<EventContext, Episode>
        {
            public override string RemoteTableName => "episode";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Episode row) => row.Id;

                public IdUniqueIndex(EpisodeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EpisodeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Episode row) => row.Id;
        }

        public readonly EpisodeHandle Episode;
    }

    public sealed class EpisodeCols
    {
        public global::SpacetimeDB.Col<Episode, int> Id { get; }
        public global::SpacetimeDB.Col<Episode, int> SeriesId { get; }
        public global::SpacetimeDB.Col<Episode, int> TvdbId { get; }
        public global::SpacetimeDB.Col<Episode, int> EpisodeFileId { get; }
        public global::SpacetimeDB.Col<Episode, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> EpisodeNumber { get; }
        public global::SpacetimeDB.Col<Episode, string> Title { get; }
        public global::SpacetimeDB.Col<Episode, string> AirDate { get; }
        public global::SpacetimeDB.Col<Episode, SpacetimeDB.Timestamp> AirDateUtc { get; }
        public global::SpacetimeDB.Col<Episode, string> Overview { get; }
        public global::SpacetimeDB.Col<Episode, bool> Monitored { get; }
        public global::SpacetimeDB.Col<Episode, int> AbsoluteEpisodeNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> SceneAbsoluteEpisodeNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> SceneSeasonNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> SceneEpisodeNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> AiredAfterSeasonNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> AiredBeforeSeasonNumber { get; }
        public global::SpacetimeDB.Col<Episode, int> AiredBeforeEpisodeNumber { get; }
        public global::SpacetimeDB.Col<Episode, bool> UnverifiedSceneNumbering { get; }
        public global::SpacetimeDB.Col<Episode, string> RatingsJson { get; }
        public global::SpacetimeDB.Col<Episode, string> ImagesJson { get; }
        public global::SpacetimeDB.Col<Episode, SpacetimeDB.Timestamp> LastSearchTime { get; }
        public global::SpacetimeDB.Col<Episode, int> Runtime { get; }
        public global::SpacetimeDB.Col<Episode, string> FinaleType { get; }

        public EpisodeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Episode, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<Episode, int>(tableName, "series_id");
            TvdbId = new global::SpacetimeDB.Col<Episode, int>(tableName, "tvdb_id");
            EpisodeFileId = new global::SpacetimeDB.Col<Episode, int>(tableName, "episode_file_id");
            SeasonNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "season_number");
            EpisodeNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "episode_number");
            Title = new global::SpacetimeDB.Col<Episode, string>(tableName, "title");
            AirDate = new global::SpacetimeDB.Col<Episode, string>(tableName, "air_date");
            AirDateUtc = new global::SpacetimeDB.Col<Episode, SpacetimeDB.Timestamp>(tableName, "air_date_utc");
            Overview = new global::SpacetimeDB.Col<Episode, string>(tableName, "overview");
            Monitored = new global::SpacetimeDB.Col<Episode, bool>(tableName, "monitored");
            AbsoluteEpisodeNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "absolute_episode_number");
            SceneAbsoluteEpisodeNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "scene_absolute_episode_number");
            SceneSeasonNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "scene_season_number");
            SceneEpisodeNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "scene_episode_number");
            AiredAfterSeasonNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "aired_after_season_number");
            AiredBeforeSeasonNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "aired_before_season_number");
            AiredBeforeEpisodeNumber = new global::SpacetimeDB.Col<Episode, int>(tableName, "aired_before_episode_number");
            UnverifiedSceneNumbering = new global::SpacetimeDB.Col<Episode, bool>(tableName, "unverified_scene_numbering");
            RatingsJson = new global::SpacetimeDB.Col<Episode, string>(tableName, "ratings_json");
            ImagesJson = new global::SpacetimeDB.Col<Episode, string>(tableName, "images_json");
            LastSearchTime = new global::SpacetimeDB.Col<Episode, SpacetimeDB.Timestamp>(tableName, "last_search_time");
            Runtime = new global::SpacetimeDB.Col<Episode, int>(tableName, "runtime");
            FinaleType = new global::SpacetimeDB.Col<Episode, string>(tableName, "finale_type");
        }
    }

    public sealed class EpisodeIxCols
    {
        public global::SpacetimeDB.IxCol<Episode, int> Id { get; }

        public EpisodeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Episode, int>(tableName, "id");
        }
    }
}
