// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EpisodeFileHandle : RemoteTableHandle<EventContext, EpisodeFile>
        {
            public override string RemoteTableName => "episode_file";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EpisodeFile row) => row.Id;

                public IdUniqueIndex(EpisodeFileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EpisodeFileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EpisodeFile row) => row.Id;
        }

        public readonly EpisodeFileHandle EpisodeFile;
    }

    public sealed class EpisodeFileCols
    {
        public global::SpacetimeDB.Col<EpisodeFile, int> Id { get; }
        public global::SpacetimeDB.Col<EpisodeFile, int> SeriesId { get; }
        public global::SpacetimeDB.Col<EpisodeFile, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> RelativePath { get; }
        public global::SpacetimeDB.Col<EpisodeFile, long> Size { get; }
        public global::SpacetimeDB.Col<EpisodeFile, SpacetimeDB.Timestamp> DateAdded { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> OriginalFilePath { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> SceneName { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> ReleaseGroup { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> ReleaseHash { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> QualityJson { get; }
        public global::SpacetimeDB.Col<EpisodeFile, int> QualityId { get; }
        public global::SpacetimeDB.Col<EpisodeFile, int> IndexerFlags { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> MediaInfoJson { get; }
        public global::SpacetimeDB.Col<EpisodeFile, string> LanguagesJson { get; }
        public global::SpacetimeDB.Col<EpisodeFile, int> ReleaseType { get; }

        public EpisodeFileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "series_id");
            SeasonNumber = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "season_number");
            RelativePath = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "relative_path");
            Size = new global::SpacetimeDB.Col<EpisodeFile, long>(tableName, "size");
            DateAdded = new global::SpacetimeDB.Col<EpisodeFile, SpacetimeDB.Timestamp>(tableName, "date_added");
            OriginalFilePath = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "original_file_path");
            SceneName = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "scene_name");
            ReleaseGroup = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "release_group");
            ReleaseHash = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "release_hash");
            QualityJson = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "quality_json");
            QualityId = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "quality_id");
            IndexerFlags = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "indexer_flags");
            MediaInfoJson = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "media_info_json");
            LanguagesJson = new global::SpacetimeDB.Col<EpisodeFile, string>(tableName, "languages_json");
            ReleaseType = new global::SpacetimeDB.Col<EpisodeFile, int>(tableName, "release_type");
        }
    }

    public sealed class EpisodeFileIxCols
    {
        public global::SpacetimeDB.IxCol<EpisodeFile, int> Id { get; }

        public EpisodeFileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EpisodeFile, int>(tableName, "id");
        }
    }
}
