// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImportListItemHandle : RemoteTableHandle<EventContext, ImportListItem>
        {
            public override string RemoteTableName => "import_list_item";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ImportListItem row) => row.Id;

                public IdUniqueIndex(ImportListItemHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ImportListItemHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ImportListItem row) => row.Id;
        }

        public readonly ImportListItemHandle ImportListItem;
    }

    public sealed class ImportListItemCols
    {
        public global::SpacetimeDB.Col<ImportListItem, int> Id { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> ImportListId { get; }
        public global::SpacetimeDB.Col<ImportListItem, string> Title { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> Year { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> TvdbId { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> TmdbId { get; }
        public global::SpacetimeDB.Col<ImportListItem, string> ImdbId { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> MalId { get; }
        public global::SpacetimeDB.Col<ImportListItem, int> AniListId { get; }
        public global::SpacetimeDB.Col<ImportListItem, SpacetimeDB.Timestamp> ReleaseDate { get; }

        public ImportListItemCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "id");
            ImportListId = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "import_list_id");
            Title = new global::SpacetimeDB.Col<ImportListItem, string>(tableName, "title");
            Year = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "year");
            TvdbId = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "tvdb_id");
            TmdbId = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "tmdb_id");
            ImdbId = new global::SpacetimeDB.Col<ImportListItem, string>(tableName, "imdb_id");
            MalId = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "mal_id");
            AniListId = new global::SpacetimeDB.Col<ImportListItem, int>(tableName, "ani_list_id");
            ReleaseDate = new global::SpacetimeDB.Col<ImportListItem, SpacetimeDB.Timestamp>(tableName, "release_date");
        }
    }

    public sealed class ImportListItemIxCols
    {
        public global::SpacetimeDB.IxCol<ImportListItem, int> Id { get; }

        public ImportListItemIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ImportListItem, int>(tableName, "id");
        }
    }
}
