// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImportListDefinitionHandle : RemoteTableHandle<EventContext, ImportListDefinition>
        {
            public override string RemoteTableName => "import_list_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ImportListDefinition row) => row.Id;

                public IdUniqueIndex(ImportListDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ImportListDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ImportListDefinition row) => row.Id;
        }

        public readonly ImportListDefinitionHandle ImportListDefinition;
    }

    public sealed class ImportListDefinitionCols
    {
        public global::SpacetimeDB.Col<ImportListDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> Implementation { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> ConfigContract { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> SettingsJson { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, bool> Enable { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> TagsJson { get; }
        public global::SpacetimeDB.Col<ImportListDefinition, string> MessageJson { get; }

        public ImportListDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ImportListDefinition, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "name");
            Implementation = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "implementation");
            ConfigContract = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "config_contract");
            SettingsJson = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "settings_json");
            Enable = new global::SpacetimeDB.Col<ImportListDefinition, bool>(tableName, "enable");
            TagsJson = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "tags_json");
            MessageJson = new global::SpacetimeDB.Col<ImportListDefinition, string>(tableName, "message_json");
        }
    }

    public sealed class ImportListDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<ImportListDefinition, int> Id { get; }

        public ImportListDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ImportListDefinition, int>(tableName, "id");
        }
    }
}
