// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImportListExclusionHandle : RemoteTableHandle<EventContext, ImportListExclusion>
        {
            public override string RemoteTableName => "import_list_exclusion";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ImportListExclusion row) => row.Id;

                public IdUniqueIndex(ImportListExclusionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ImportListExclusionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ImportListExclusion row) => row.Id;
        }

        public readonly ImportListExclusionHandle ImportListExclusion;
    }

    public sealed class ImportListExclusionCols
    {
        public global::SpacetimeDB.Col<ImportListExclusion, int> Id { get; }
        public global::SpacetimeDB.Col<ImportListExclusion, int> TvdbId { get; }
        public global::SpacetimeDB.Col<ImportListExclusion, string> Title { get; }

        public ImportListExclusionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ImportListExclusion, int>(tableName, "id");
            TvdbId = new global::SpacetimeDB.Col<ImportListExclusion, int>(tableName, "tvdb_id");
            Title = new global::SpacetimeDB.Col<ImportListExclusion, string>(tableName, "title");
        }
    }

    public sealed class ImportListExclusionIxCols
    {
        public global::SpacetimeDB.IxCol<ImportListExclusion, int> Id { get; }

        public ImportListExclusionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ImportListExclusion, int>(tableName, "id");
        }
    }
}
