// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class IndexerDefinitionHandle : RemoteTableHandle<EventContext, IndexerDefinition>
        {
            public override string RemoteTableName => "indexer_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(IndexerDefinition row) => row.Id;

                public IdUniqueIndex(IndexerDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal IndexerDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(IndexerDefinition row) => row.Id;
        }

        public readonly IndexerDefinitionHandle IndexerDefinition;
    }

    public sealed class IndexerDefinitionCols
    {
        public global::SpacetimeDB.Col<IndexerDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> Implementation { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> ConfigContract { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> SettingsJson { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, bool> Enable { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> TagsJson { get; }
        public global::SpacetimeDB.Col<IndexerDefinition, string> MessageJson { get; }

        public IndexerDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<IndexerDefinition, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "name");
            Implementation = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "implementation");
            ConfigContract = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "config_contract");
            SettingsJson = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "settings_json");
            Enable = new global::SpacetimeDB.Col<IndexerDefinition, bool>(tableName, "enable");
            TagsJson = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "tags_json");
            MessageJson = new global::SpacetimeDB.Col<IndexerDefinition, string>(tableName, "message_json");
        }
    }

    public sealed class IndexerDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<IndexerDefinition, int> Id { get; }

        public IndexerDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<IndexerDefinition, int>(tableName, "id");
        }
    }
}
