// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class IndexerStatusHandle : RemoteTableHandle<EventContext, IndexerStatus>
        {
            public override string RemoteTableName => "indexer_status";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(IndexerStatus row) => row.Id;

                public IdUniqueIndex(IndexerStatusHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal IndexerStatusHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(IndexerStatus row) => row.Id;
        }

        public readonly IndexerStatusHandle IndexerStatus;
    }

    public sealed class IndexerStatusCols
    {
        public global::SpacetimeDB.Col<IndexerStatus, int> Id { get; }
        public global::SpacetimeDB.Col<IndexerStatus, int> ProviderId { get; }
        public global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp> InitialFailure { get; }
        public global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp> MostRecentFailure { get; }
        public global::SpacetimeDB.Col<IndexerStatus, int> EscalationLevel { get; }
        public global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp> DisabledTill { get; }
        public global::SpacetimeDB.Col<IndexerStatus, string> LastRssSyncReleaseInfoJson { get; }

        public IndexerStatusCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<IndexerStatus, int>(tableName, "id");
            ProviderId = new global::SpacetimeDB.Col<IndexerStatus, int>(tableName, "provider_id");
            InitialFailure = new global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp>(tableName, "initial_failure");
            MostRecentFailure = new global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp>(tableName, "most_recent_failure");
            EscalationLevel = new global::SpacetimeDB.Col<IndexerStatus, int>(tableName, "escalation_level");
            DisabledTill = new global::SpacetimeDB.Col<IndexerStatus, SpacetimeDB.Timestamp>(tableName, "disabled_till");
            LastRssSyncReleaseInfoJson = new global::SpacetimeDB.Col<IndexerStatus, string>(tableName, "last_rss_sync_release_info_json");
        }
    }

    public sealed class IndexerStatusIxCols
    {
        public global::SpacetimeDB.IxCol<IndexerStatus, int> Id { get; }

        public IndexerStatusIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<IndexerStatus, int>(tableName, "id");
        }
    }
}
