// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MetadataDefinitionHandle : RemoteTableHandle<EventContext, MetadataDefinition>
        {
            public override string RemoteTableName => "metadata_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(MetadataDefinition row) => row.Id;

                public IdUniqueIndex(MetadataDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MetadataDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(MetadataDefinition row) => row.Id;
        }

        public readonly MetadataDefinitionHandle MetadataDefinition;
    }

    public sealed class MetadataDefinitionCols
    {
        public global::SpacetimeDB.Col<MetadataDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> Implementation { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> ConfigContract { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> SettingsJson { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, bool> Enable { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> TagsJson { get; }
        public global::SpacetimeDB.Col<MetadataDefinition, string> MessageJson { get; }

        public MetadataDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MetadataDefinition, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "name");
            Implementation = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "implementation");
            ConfigContract = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "config_contract");
            SettingsJson = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "settings_json");
            Enable = new global::SpacetimeDB.Col<MetadataDefinition, bool>(tableName, "enable");
            TagsJson = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "tags_json");
            MessageJson = new global::SpacetimeDB.Col<MetadataDefinition, string>(tableName, "message_json");
        }
    }

    public sealed class MetadataDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<MetadataDefinition, int> Id { get; }

        public MetadataDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MetadataDefinition, int>(tableName, "id");
        }
    }
}
