// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MetadataFileHandle : RemoteTableHandle<EventContext, MetadataFile>
        {
            public override string RemoteTableName => "metadata_file";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(MetadataFile row) => row.Id;

                public IdUniqueIndex(MetadataFileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MetadataFileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(MetadataFile row) => row.Id;
        }

        public readonly MetadataFileHandle MetadataFile;
    }

    public sealed class MetadataFileCols
    {
        public global::SpacetimeDB.Col<MetadataFile, int> Id { get; }
        public global::SpacetimeDB.Col<MetadataFile, int> SeriesId { get; }
        public global::SpacetimeDB.Col<MetadataFile, int> EpisodeFileId { get; }
        public global::SpacetimeDB.Col<MetadataFile, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<MetadataFile, string> RelativePath { get; }
        public global::SpacetimeDB.Col<MetadataFile, SpacetimeDB.Timestamp> Added { get; }
        public global::SpacetimeDB.Col<MetadataFile, SpacetimeDB.Timestamp> LastUpdated { get; }
        public global::SpacetimeDB.Col<MetadataFile, string> Extension { get; }
        public global::SpacetimeDB.Col<MetadataFile, string> Hash { get; }
        public global::SpacetimeDB.Col<MetadataFile, string> Consumer { get; }
        public global::SpacetimeDB.Col<MetadataFile, int> Type { get; }

        public MetadataFileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MetadataFile, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<MetadataFile, int>(tableName, "series_id");
            EpisodeFileId = new global::SpacetimeDB.Col<MetadataFile, int>(tableName, "episode_file_id");
            SeasonNumber = new global::SpacetimeDB.Col<MetadataFile, int>(tableName, "season_number");
            RelativePath = new global::SpacetimeDB.Col<MetadataFile, string>(tableName, "relative_path");
            Added = new global::SpacetimeDB.Col<MetadataFile, SpacetimeDB.Timestamp>(tableName, "added");
            LastUpdated = new global::SpacetimeDB.Col<MetadataFile, SpacetimeDB.Timestamp>(tableName, "last_updated");
            Extension = new global::SpacetimeDB.Col<MetadataFile, string>(tableName, "extension");
            Hash = new global::SpacetimeDB.Col<MetadataFile, string>(tableName, "hash");
            Consumer = new global::SpacetimeDB.Col<MetadataFile, string>(tableName, "consumer");
            Type = new global::SpacetimeDB.Col<MetadataFile, int>(tableName, "type");
        }
    }

    public sealed class MetadataFileIxCols
    {
        public global::SpacetimeDB.IxCol<MetadataFile, int> Id { get; }

        public MetadataFileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MetadataFile, int>(tableName, "id");
        }
    }
}
