// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NamingConfigHandle : RemoteTableHandle<EventContext, NamingConfig>
        {
            public override string RemoteTableName => "naming_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(NamingConfig row) => row.Id;

                public IdUniqueIndex(NamingConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NamingConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NamingConfig row) => row.Id;
        }

        public readonly NamingConfigHandle NamingConfig;
    }

    public sealed class NamingConfigCols
    {
        public global::SpacetimeDB.Col<NamingConfig, int> Id { get; }
        public global::SpacetimeDB.Col<NamingConfig, bool> RenameEpisodes { get; }
        public global::SpacetimeDB.Col<NamingConfig, bool> ReplaceIllegalCharacters { get; }
        public global::SpacetimeDB.Col<NamingConfig, int> ColonReplacementFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> CustomColonReplacementFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, int> MultiEpisodeStyle { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> StandardEpisodeFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> DailyEpisodeFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> AnimeEpisodeFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> SeriesFolderFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> SeasonFolderFormat { get; }
        public global::SpacetimeDB.Col<NamingConfig, string> SpecialsFolderFormat { get; }

        public NamingConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NamingConfig, int>(tableName, "id");
            RenameEpisodes = new global::SpacetimeDB.Col<NamingConfig, bool>(tableName, "rename_episodes");
            ReplaceIllegalCharacters = new global::SpacetimeDB.Col<NamingConfig, bool>(tableName, "replace_illegal_characters");
            ColonReplacementFormat = new global::SpacetimeDB.Col<NamingConfig, int>(tableName, "colon_replacement_format");
            CustomColonReplacementFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "custom_colon_replacement_format");
            MultiEpisodeStyle = new global::SpacetimeDB.Col<NamingConfig, int>(tableName, "multi_episode_style");
            StandardEpisodeFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "standard_episode_format");
            DailyEpisodeFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "daily_episode_format");
            AnimeEpisodeFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "anime_episode_format");
            SeriesFolderFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "series_folder_format");
            SeasonFolderFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "season_folder_format");
            SpecialsFolderFormat = new global::SpacetimeDB.Col<NamingConfig, string>(tableName, "specials_folder_format");
        }
    }

    public sealed class NamingConfigIxCols
    {
        public global::SpacetimeDB.IxCol<NamingConfig, int> Id { get; }

        public NamingConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NamingConfig, int>(tableName, "id");
        }
    }
}
