// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NotificationDefinitionHandle : RemoteTableHandle<EventContext, NotificationDefinition>
        {
            public override string RemoteTableName => "notification_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(NotificationDefinition row) => row.Id;

                public IdUniqueIndex(NotificationDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NotificationDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NotificationDefinition row) => row.Id;
        }

        public readonly NotificationDefinitionHandle NotificationDefinition;
    }

    public sealed class NotificationDefinitionCols
    {
        public global::SpacetimeDB.Col<NotificationDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> Implementation { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> ConfigContract { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> SettingsJson { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, bool> Enable { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> TagsJson { get; }
        public global::SpacetimeDB.Col<NotificationDefinition, string> MessageJson { get; }

        public NotificationDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NotificationDefinition, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "name");
            Implementation = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "implementation");
            ConfigContract = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "config_contract");
            SettingsJson = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "settings_json");
            Enable = new global::SpacetimeDB.Col<NotificationDefinition, bool>(tableName, "enable");
            TagsJson = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "tags_json");
            MessageJson = new global::SpacetimeDB.Col<NotificationDefinition, string>(tableName, "message_json");
        }
    }

    public sealed class NotificationDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<NotificationDefinition, int> Id { get; }

        public NotificationDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NotificationDefinition, int>(tableName, "id");
        }
    }
}
