// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NotificationStatusHandle : RemoteTableHandle<EventContext, NotificationStatus>
        {
            public override string RemoteTableName => "notification_status";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(NotificationStatus row) => row.Id;

                public IdUniqueIndex(NotificationStatusHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NotificationStatusHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NotificationStatus row) => row.Id;
        }

        public readonly NotificationStatusHandle NotificationStatus;
    }

    public sealed class NotificationStatusCols
    {
        public global::SpacetimeDB.Col<NotificationStatus, int> Id { get; }
        public global::SpacetimeDB.Col<NotificationStatus, int> ProviderId { get; }
        public global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp> InitialFailure { get; }
        public global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp> MostRecentFailure { get; }
        public global::SpacetimeDB.Col<NotificationStatus, int> EscalationLevel { get; }
        public global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp> DisabledTill { get; }

        public NotificationStatusCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NotificationStatus, int>(tableName, "id");
            ProviderId = new global::SpacetimeDB.Col<NotificationStatus, int>(tableName, "provider_id");
            InitialFailure = new global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp>(tableName, "initial_failure");
            MostRecentFailure = new global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp>(tableName, "most_recent_failure");
            EscalationLevel = new global::SpacetimeDB.Col<NotificationStatus, int>(tableName, "escalation_level");
            DisabledTill = new global::SpacetimeDB.Col<NotificationStatus, SpacetimeDB.Timestamp>(tableName, "disabled_till");
        }
    }

    public sealed class NotificationStatusIxCols
    {
        public global::SpacetimeDB.IxCol<NotificationStatus, int> Id { get; }

        public NotificationStatusIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NotificationStatus, int>(tableName, "id");
        }
    }
}
