// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OtherExtraFileHandle : RemoteTableHandle<EventContext, OtherExtraFile>
        {
            public override string RemoteTableName => "other_extra_file";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(OtherExtraFile row) => row.Id;

                public IdUniqueIndex(OtherExtraFileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OtherExtraFileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(OtherExtraFile row) => row.Id;
        }

        public readonly OtherExtraFileHandle OtherExtraFile;
    }

    public sealed class OtherExtraFileCols
    {
        public global::SpacetimeDB.Col<OtherExtraFile, int> Id { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, int> SeriesId { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, int> EpisodeFileId { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, string> RelativePath { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, SpacetimeDB.Timestamp> Added { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, SpacetimeDB.Timestamp> LastUpdated { get; }
        public global::SpacetimeDB.Col<OtherExtraFile, string> Extension { get; }

        public OtherExtraFileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<OtherExtraFile, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<OtherExtraFile, int>(tableName, "series_id");
            EpisodeFileId = new global::SpacetimeDB.Col<OtherExtraFile, int>(tableName, "episode_file_id");
            SeasonNumber = new global::SpacetimeDB.Col<OtherExtraFile, int>(tableName, "season_number");
            RelativePath = new global::SpacetimeDB.Col<OtherExtraFile, string>(tableName, "relative_path");
            Added = new global::SpacetimeDB.Col<OtherExtraFile, SpacetimeDB.Timestamp>(tableName, "added");
            LastUpdated = new global::SpacetimeDB.Col<OtherExtraFile, SpacetimeDB.Timestamp>(tableName, "last_updated");
            Extension = new global::SpacetimeDB.Col<OtherExtraFile, string>(tableName, "extension");
        }
    }

    public sealed class OtherExtraFileIxCols
    {
        public global::SpacetimeDB.IxCol<OtherExtraFile, int> Id { get; }

        public OtherExtraFileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<OtherExtraFile, int>(tableName, "id");
        }
    }
}
