// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PendingReleaseHandle : RemoteTableHandle<EventContext, PendingRelease>
        {
            public override string RemoteTableName => "pending_release";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PendingRelease row) => row.Id;

                public IdUniqueIndex(PendingReleaseHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PendingReleaseHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PendingRelease row) => row.Id;
        }

        public readonly PendingReleaseHandle PendingRelease;
    }

    public sealed class PendingReleaseCols
    {
        public global::SpacetimeDB.Col<PendingRelease, int> Id { get; }
        public global::SpacetimeDB.Col<PendingRelease, int> SeriesId { get; }
        public global::SpacetimeDB.Col<PendingRelease, string> Title { get; }
        public global::SpacetimeDB.Col<PendingRelease, SpacetimeDB.Timestamp> Added { get; }
        public global::SpacetimeDB.Col<PendingRelease, string> ParsedEpisodeInfoJson { get; }
        public global::SpacetimeDB.Col<PendingRelease, string> ReleaseJson { get; }
        public global::SpacetimeDB.Col<PendingRelease, int> Reason { get; }
        public global::SpacetimeDB.Col<PendingRelease, string> AdditionalInfoJson { get; }

        public PendingReleaseCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PendingRelease, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<PendingRelease, int>(tableName, "series_id");
            Title = new global::SpacetimeDB.Col<PendingRelease, string>(tableName, "title");
            Added = new global::SpacetimeDB.Col<PendingRelease, SpacetimeDB.Timestamp>(tableName, "added");
            ParsedEpisodeInfoJson = new global::SpacetimeDB.Col<PendingRelease, string>(tableName, "parsed_episode_info_json");
            ReleaseJson = new global::SpacetimeDB.Col<PendingRelease, string>(tableName, "release_json");
            Reason = new global::SpacetimeDB.Col<PendingRelease, int>(tableName, "reason");
            AdditionalInfoJson = new global::SpacetimeDB.Col<PendingRelease, string>(tableName, "additional_info_json");
        }
    }

    public sealed class PendingReleaseIxCols
    {
        public global::SpacetimeDB.IxCol<PendingRelease, int> Id { get; }

        public PendingReleaseIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PendingRelease, int>(tableName, "id");
        }
    }
}
