// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QualityProfileQualityRankHandle : RemoteTableHandle<EventContext, QualityProfileQualityRank>
        {
            public override string RemoteTableName => "quality_profile_quality_rank";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(QualityProfileQualityRank row) => row.Id;

                public IdUniqueIndex(QualityProfileQualityRankHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal QualityProfileQualityRankHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(QualityProfileQualityRank row) => row.Id;
        }

        public readonly QualityProfileQualityRankHandle QualityProfileQualityRank;
    }

    public sealed class QualityProfileQualityRankCols
    {
        public global::SpacetimeDB.Col<QualityProfileQualityRank, int> Id { get; }
        public global::SpacetimeDB.Col<QualityProfileQualityRank, int> ProfileId { get; }
        public global::SpacetimeDB.Col<QualityProfileQualityRank, int> QualityId { get; }
        public global::SpacetimeDB.Col<QualityProfileQualityRank, double> Score { get; }

        public QualityProfileQualityRankCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<QualityProfileQualityRank, int>(tableName, "id");
            ProfileId = new global::SpacetimeDB.Col<QualityProfileQualityRank, int>(tableName, "profile_id");
            QualityId = new global::SpacetimeDB.Col<QualityProfileQualityRank, int>(tableName, "quality_id");
            Score = new global::SpacetimeDB.Col<QualityProfileQualityRank, double>(tableName, "score");
        }
    }

    public sealed class QualityProfileQualityRankIxCols
    {
        public global::SpacetimeDB.IxCol<QualityProfileQualityRank, int> Id { get; }

        public QualityProfileQualityRankIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<QualityProfileQualityRank, int>(tableName, "id");
        }
    }
}
