// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QualityDefinitionHandle : RemoteTableHandle<EventContext, QualityDefinition>
        {
            public override string RemoteTableName => "quality_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(QualityDefinition row) => row.Id;

                public IdUniqueIndex(QualityDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal QualityDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(QualityDefinition row) => row.Id;
        }

        public readonly QualityDefinitionHandle QualityDefinition;
    }

    public sealed class QualityDefinitionCols
    {
        public global::SpacetimeDB.Col<QualityDefinition, int> Id { get; }
        public global::SpacetimeDB.Col<QualityDefinition, string> QualityJson { get; }
        public global::SpacetimeDB.Col<QualityDefinition, string> Title { get; }

        public QualityDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<QualityDefinition, int>(tableName, "id");
            QualityJson = new global::SpacetimeDB.Col<QualityDefinition, string>(tableName, "quality_json");
            Title = new global::SpacetimeDB.Col<QualityDefinition, string>(tableName, "title");
        }
    }

    public sealed class QualityDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<QualityDefinition, int> Id { get; }

        public QualityDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<QualityDefinition, int>(tableName, "id");
        }
    }
}
