// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QualityProfileHandle : RemoteTableHandle<EventContext, QualityProfile>
        {
            public override string RemoteTableName => "quality_profile";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(QualityProfile row) => row.Id;

                public IdUniqueIndex(QualityProfileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal QualityProfileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(QualityProfile row) => row.Id;
        }

        public readonly QualityProfileHandle QualityProfile;
    }

    public sealed class QualityProfileCols
    {
        public global::SpacetimeDB.Col<QualityProfile, int> Id { get; }
        public global::SpacetimeDB.Col<QualityProfile, string> Name { get; }
        public global::SpacetimeDB.Col<QualityProfile, bool> UpgradeAllowed { get; }
        public global::SpacetimeDB.Col<QualityProfile, int> Cutoff { get; }
        public global::SpacetimeDB.Col<QualityProfile, int> MinFormatScore { get; }
        public global::SpacetimeDB.Col<QualityProfile, int> CutoffFormatScore { get; }
        public global::SpacetimeDB.Col<QualityProfile, int> MinUpgradeFormatScore { get; }
        public global::SpacetimeDB.Col<QualityProfile, string> FormatItemsJson { get; }
        public global::SpacetimeDB.Col<QualityProfile, string> ItemsJson { get; }

        public QualityProfileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<QualityProfile, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<QualityProfile, string>(tableName, "name");
            UpgradeAllowed = new global::SpacetimeDB.Col<QualityProfile, bool>(tableName, "upgrade_allowed");
            Cutoff = new global::SpacetimeDB.Col<QualityProfile, int>(tableName, "cutoff");
            MinFormatScore = new global::SpacetimeDB.Col<QualityProfile, int>(tableName, "min_format_score");
            CutoffFormatScore = new global::SpacetimeDB.Col<QualityProfile, int>(tableName, "cutoff_format_score");
            MinUpgradeFormatScore = new global::SpacetimeDB.Col<QualityProfile, int>(tableName, "min_upgrade_format_score");
            FormatItemsJson = new global::SpacetimeDB.Col<QualityProfile, string>(tableName, "format_items_json");
            ItemsJson = new global::SpacetimeDB.Col<QualityProfile, string>(tableName, "items_json");
        }
    }

    public sealed class QualityProfileIxCols
    {
        public global::SpacetimeDB.IxCol<QualityProfile, int> Id { get; }

        public QualityProfileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<QualityProfile, int>(tableName, "id");
        }
    }
}
