// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ReleaseProfileHandle : RemoteTableHandle<EventContext, ReleaseProfile>
        {
            public override string RemoteTableName => "release_profile";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ReleaseProfile row) => row.Id;

                public IdUniqueIndex(ReleaseProfileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ReleaseProfileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ReleaseProfile row) => row.Id;
        }

        public readonly ReleaseProfileHandle ReleaseProfile;
    }

    public sealed class ReleaseProfileCols
    {
        public global::SpacetimeDB.Col<ReleaseProfile, int> Id { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> Name { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, bool> Enabled { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> RequiredJson { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> IgnoredJson { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, bool> AirDateRestriction { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, int> AirDateGracePeriod { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, bool> AllowSeasonPackWithoutAllEpisodesAired { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> IndexerIdsJson { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> TagsJson { get; }
        public global::SpacetimeDB.Col<ReleaseProfile, string> ExcludedTagsJson { get; }

        public ReleaseProfileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ReleaseProfile, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "name");
            Enabled = new global::SpacetimeDB.Col<ReleaseProfile, bool>(tableName, "enabled");
            RequiredJson = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "required_json");
            IgnoredJson = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "ignored_json");
            AirDateRestriction = new global::SpacetimeDB.Col<ReleaseProfile, bool>(tableName, "air_date_restriction");
            AirDateGracePeriod = new global::SpacetimeDB.Col<ReleaseProfile, int>(tableName, "air_date_grace_period");
            AllowSeasonPackWithoutAllEpisodesAired = new global::SpacetimeDB.Col<ReleaseProfile, bool>(tableName, "allow_season_pack_without_all_episodes_aired");
            IndexerIdsJson = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "indexer_ids_json");
            TagsJson = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "tags_json");
            ExcludedTagsJson = new global::SpacetimeDB.Col<ReleaseProfile, string>(tableName, "excluded_tags_json");
        }
    }

    public sealed class ReleaseProfileIxCols
    {
        public global::SpacetimeDB.IxCol<ReleaseProfile, int> Id { get; }

        public ReleaseProfileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ReleaseProfile, int>(tableName, "id");
        }
    }
}
