// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SceneMappingHandle : RemoteTableHandle<EventContext, SceneMapping>
        {
            public override string RemoteTableName => "scene_mapping";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SceneMapping row) => row.Id;

                public IdUniqueIndex(SceneMappingHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SceneMappingHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SceneMapping row) => row.Id;
        }

        public readonly SceneMappingHandle SceneMapping;
    }

    public sealed class SceneMappingCols
    {
        public global::SpacetimeDB.Col<SceneMapping, int> Id { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> MappingId { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> Title { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> ParseTerm { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> SearchTerm { get; }
        public global::SpacetimeDB.Col<SceneMapping, int> TvdbId { get; }
        public global::SpacetimeDB.Col<SceneMapping, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<SceneMapping, int> SceneSeasonNumber { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> SceneOrigin { get; }
        public global::SpacetimeDB.Col<SceneMapping, int> SearchMode { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> Comment { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> FilterRegex { get; }
        public global::SpacetimeDB.Col<SceneMapping, string> Type { get; }

        public SceneMappingCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SceneMapping, int>(tableName, "id");
            MappingId = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "mapping_id");
            Title = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "title");
            ParseTerm = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "parse_term");
            SearchTerm = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "search_term");
            TvdbId = new global::SpacetimeDB.Col<SceneMapping, int>(tableName, "tvdb_id");
            SeasonNumber = new global::SpacetimeDB.Col<SceneMapping, int>(tableName, "season_number");
            SceneSeasonNumber = new global::SpacetimeDB.Col<SceneMapping, int>(tableName, "scene_season_number");
            SceneOrigin = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "scene_origin");
            SearchMode = new global::SpacetimeDB.Col<SceneMapping, int>(tableName, "search_mode");
            Comment = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "comment");
            FilterRegex = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "filter_regex");
            Type = new global::SpacetimeDB.Col<SceneMapping, string>(tableName, "type");
        }
    }

    public sealed class SceneMappingIxCols
    {
        public global::SpacetimeDB.IxCol<SceneMapping, int> Id { get; }

        public SceneMappingIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SceneMapping, int>(tableName, "id");
        }
    }
}
