// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SeriesTagHandle : RemoteTableHandle<EventContext, SeriesTag>
        {
            public override string RemoteTableName => "series_tag";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SeriesTag row) => row.Id;

                public IdUniqueIndex(SeriesTagHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SeriesIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(SeriesTag row) => row.SeriesId;

                public SeriesIdIndex(SeriesTagHandle table) : base(table) { }
            }

            public readonly SeriesIdIndex SeriesId;

            internal SeriesTagHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                SeriesId = new(this);
            }

            protected override object GetPrimaryKey(SeriesTag row) => row.Id;
        }

        public readonly SeriesTagHandle SeriesTag;
    }

    public sealed class SeriesTagCols
    {
        public global::SpacetimeDB.Col<SeriesTag, int> Id { get; }
        public global::SpacetimeDB.Col<SeriesTag, int> SeriesId { get; }
        public global::SpacetimeDB.Col<SeriesTag, int> TagId { get; }

        public SeriesTagCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SeriesTag, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<SeriesTag, int>(tableName, "series_id");
            TagId = new global::SpacetimeDB.Col<SeriesTag, int>(tableName, "tag_id");
        }
    }

    public sealed class SeriesTagIxCols
    {
        public global::SpacetimeDB.IxCol<SeriesTag, int> Id { get; }
        public global::SpacetimeDB.IxCol<SeriesTag, int> SeriesId { get; }

        public SeriesTagIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SeriesTag, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.IxCol<SeriesTag, int>(tableName, "series_id");
        }
    }
}
