// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SeriesHandle : RemoteTableHandle<EventContext, Series>
        {
            public override string RemoteTableName => "series";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Series row) => row.Id;

                public IdUniqueIndex(SeriesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SeriesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Series row) => row.Id;
        }

        public readonly SeriesHandle Series;
    }

    public sealed class SeriesCols
    {
        public global::SpacetimeDB.Col<Series, int> Id { get; }
        public global::SpacetimeDB.Col<Series, int> TvdbId { get; }
        public global::SpacetimeDB.Col<Series, int> TvRageId { get; }
        public global::SpacetimeDB.Col<Series, int> TvMazeId { get; }
        public global::SpacetimeDB.Col<Series, string> ImdbId { get; }
        public global::SpacetimeDB.Col<Series, int> TmdbId { get; }
        public global::SpacetimeDB.Col<Series, string> MalIdsJson { get; }
        public global::SpacetimeDB.Col<Series, string> AniListIdsJson { get; }
        public global::SpacetimeDB.Col<Series, string> Title { get; }
        public global::SpacetimeDB.Col<Series, string> CleanTitle { get; }
        public global::SpacetimeDB.Col<Series, string> SortTitle { get; }
        public global::SpacetimeDB.Col<Series, int> Status { get; }
        public global::SpacetimeDB.Col<Series, string> Overview { get; }
        public global::SpacetimeDB.Col<Series, string> AirTime { get; }
        public global::SpacetimeDB.Col<Series, bool> Monitored { get; }
        public global::SpacetimeDB.Col<Series, int> MonitorNewItems { get; }
        public global::SpacetimeDB.Col<Series, int> QualityProfileId { get; }
        public global::SpacetimeDB.Col<Series, bool> SeasonFolder { get; }
        public global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp> LastInfoSync { get; }
        public global::SpacetimeDB.Col<Series, int> Runtime { get; }
        public global::SpacetimeDB.Col<Series, string> ImagesJson { get; }
        public global::SpacetimeDB.Col<Series, int> SeriesType { get; }
        public global::SpacetimeDB.Col<Series, string> Network { get; }
        public global::SpacetimeDB.Col<Series, bool> UseSceneNumbering { get; }
        public global::SpacetimeDB.Col<Series, string> TitleSlug { get; }
        public global::SpacetimeDB.Col<Series, string> Path { get; }
        public global::SpacetimeDB.Col<Series, int> Year { get; }
        public global::SpacetimeDB.Col<Series, string> RatingsJson { get; }
        public global::SpacetimeDB.Col<Series, string> GenresJson { get; }
        public global::SpacetimeDB.Col<Series, string> ActorsJson { get; }
        public global::SpacetimeDB.Col<Series, string> Certification { get; }
        public global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp> Added { get; }
        public global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp> FirstAired { get; }
        public global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp> LastAired { get; }
        public global::SpacetimeDB.Col<Series, string> OriginalLanguageJson { get; }
        public global::SpacetimeDB.Col<Series, string> OriginalCountry { get; }
        public global::SpacetimeDB.Col<Series, string> SeasonsJson { get; }
        public global::SpacetimeDB.Col<Series, string> AddOptionsJson { get; }

        public SeriesCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Series, int>(tableName, "id");
            TvdbId = new global::SpacetimeDB.Col<Series, int>(tableName, "tvdb_id");
            TvRageId = new global::SpacetimeDB.Col<Series, int>(tableName, "tv_rage_id");
            TvMazeId = new global::SpacetimeDB.Col<Series, int>(tableName, "tv_maze_id");
            ImdbId = new global::SpacetimeDB.Col<Series, string>(tableName, "imdb_id");
            TmdbId = new global::SpacetimeDB.Col<Series, int>(tableName, "tmdb_id");
            MalIdsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "mal_ids_json");
            AniListIdsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "ani_list_ids_json");
            Title = new global::SpacetimeDB.Col<Series, string>(tableName, "title");
            CleanTitle = new global::SpacetimeDB.Col<Series, string>(tableName, "clean_title");
            SortTitle = new global::SpacetimeDB.Col<Series, string>(tableName, "sort_title");
            Status = new global::SpacetimeDB.Col<Series, int>(tableName, "status");
            Overview = new global::SpacetimeDB.Col<Series, string>(tableName, "overview");
            AirTime = new global::SpacetimeDB.Col<Series, string>(tableName, "air_time");
            Monitored = new global::SpacetimeDB.Col<Series, bool>(tableName, "monitored");
            MonitorNewItems = new global::SpacetimeDB.Col<Series, int>(tableName, "monitor_new_items");
            QualityProfileId = new global::SpacetimeDB.Col<Series, int>(tableName, "quality_profile_id");
            SeasonFolder = new global::SpacetimeDB.Col<Series, bool>(tableName, "season_folder");
            LastInfoSync = new global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp>(tableName, "last_info_sync");
            Runtime = new global::SpacetimeDB.Col<Series, int>(tableName, "runtime");
            ImagesJson = new global::SpacetimeDB.Col<Series, string>(tableName, "images_json");
            SeriesType = new global::SpacetimeDB.Col<Series, int>(tableName, "series_type");
            Network = new global::SpacetimeDB.Col<Series, string>(tableName, "network");
            UseSceneNumbering = new global::SpacetimeDB.Col<Series, bool>(tableName, "use_scene_numbering");
            TitleSlug = new global::SpacetimeDB.Col<Series, string>(tableName, "title_slug");
            Path = new global::SpacetimeDB.Col<Series, string>(tableName, "path");
            Year = new global::SpacetimeDB.Col<Series, int>(tableName, "year");
            RatingsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "ratings_json");
            GenresJson = new global::SpacetimeDB.Col<Series, string>(tableName, "genres_json");
            ActorsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "actors_json");
            Certification = new global::SpacetimeDB.Col<Series, string>(tableName, "certification");
            Added = new global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp>(tableName, "added");
            FirstAired = new global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp>(tableName, "first_aired");
            LastAired = new global::SpacetimeDB.Col<Series, SpacetimeDB.Timestamp>(tableName, "last_aired");
            OriginalLanguageJson = new global::SpacetimeDB.Col<Series, string>(tableName, "original_language_json");
            OriginalCountry = new global::SpacetimeDB.Col<Series, string>(tableName, "original_country");
            SeasonsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "seasons_json");
            AddOptionsJson = new global::SpacetimeDB.Col<Series, string>(tableName, "add_options_json");
        }
    }

    public sealed class SeriesIxCols
    {
        public global::SpacetimeDB.IxCol<Series, int> Id { get; }

        public SeriesIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Series, int>(tableName, "id");
        }
    }
}
