// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SubtitleFileHandle : RemoteTableHandle<EventContext, SubtitleFile>
        {
            public override string RemoteTableName => "subtitle_file";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SubtitleFile row) => row.Id;

                public IdUniqueIndex(SubtitleFileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SubtitleFileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SubtitleFile row) => row.Id;
        }

        public readonly SubtitleFileHandle SubtitleFile;
    }

    public sealed class SubtitleFileCols
    {
        public global::SpacetimeDB.Col<SubtitleFile, int> Id { get; }
        public global::SpacetimeDB.Col<SubtitleFile, int> SeriesId { get; }
        public global::SpacetimeDB.Col<SubtitleFile, int> EpisodeFileId { get; }
        public global::SpacetimeDB.Col<SubtitleFile, int> SeasonNumber { get; }
        public global::SpacetimeDB.Col<SubtitleFile, string> RelativePath { get; }
        public global::SpacetimeDB.Col<SubtitleFile, SpacetimeDB.Timestamp> Added { get; }
        public global::SpacetimeDB.Col<SubtitleFile, SpacetimeDB.Timestamp> LastUpdated { get; }
        public global::SpacetimeDB.Col<SubtitleFile, string> Extension { get; }
        public global::SpacetimeDB.Col<SubtitleFile, string> LanguageJson { get; }
        public global::SpacetimeDB.Col<SubtitleFile, int> Copy { get; }
        public global::SpacetimeDB.Col<SubtitleFile, string> LanguageTagsJson { get; }
        public global::SpacetimeDB.Col<SubtitleFile, string> Title { get; }

        public SubtitleFileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SubtitleFile, int>(tableName, "id");
            SeriesId = new global::SpacetimeDB.Col<SubtitleFile, int>(tableName, "series_id");
            EpisodeFileId = new global::SpacetimeDB.Col<SubtitleFile, int>(tableName, "episode_file_id");
            SeasonNumber = new global::SpacetimeDB.Col<SubtitleFile, int>(tableName, "season_number");
            RelativePath = new global::SpacetimeDB.Col<SubtitleFile, string>(tableName, "relative_path");
            Added = new global::SpacetimeDB.Col<SubtitleFile, SpacetimeDB.Timestamp>(tableName, "added");
            LastUpdated = new global::SpacetimeDB.Col<SubtitleFile, SpacetimeDB.Timestamp>(tableName, "last_updated");
            Extension = new global::SpacetimeDB.Col<SubtitleFile, string>(tableName, "extension");
            LanguageJson = new global::SpacetimeDB.Col<SubtitleFile, string>(tableName, "language_json");
            Copy = new global::SpacetimeDB.Col<SubtitleFile, int>(tableName, "copy");
            LanguageTagsJson = new global::SpacetimeDB.Col<SubtitleFile, string>(tableName, "language_tags_json");
            Title = new global::SpacetimeDB.Col<SubtitleFile, string>(tableName, "title");
        }
    }

    public sealed class SubtitleFileIxCols
    {
        public global::SpacetimeDB.IxCol<SubtitleFile, int> Id { get; }

        public SubtitleFileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SubtitleFile, int>(tableName, "id");
        }
    }
}
