// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrustedConfigsHandle : RemoteTableHandle<EventContext, Config>
        {
            public override string RemoteTableName => "trusted_configs";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Config row) => row.Id;

                public IdUniqueIndex(TrustedConfigsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TrustedConfigsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Config row) => row.Id;
        }

        public readonly TrustedConfigsHandle TrustedConfigs;
    }

    public sealed class TrustedConfigsCols
    {
        public global::SpacetimeDB.Col<Config, int> Id { get; }
        public global::SpacetimeDB.Col<Config, string> Key { get; }
        public global::SpacetimeDB.Col<Config, string> Value { get; }

        public TrustedConfigsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Config, int>(tableName, "id");
            Key = new global::SpacetimeDB.Col<Config, string>(tableName, "key");
            Value = new global::SpacetimeDB.Col<Config, string>(tableName, "value");
        }
    }

    public sealed class TrustedConfigsIxCols
    {
        public global::SpacetimeDB.IxCol<Config, int> Id { get; }

        public TrustedConfigsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Config, int>(tableName, "id");
        }
    }
}
