// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrustedUsersHandle : RemoteTableHandle<EventContext, User>
        {
            public override string RemoteTableName => "trusted_users";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(User row) => row.Id;

                public IdUniqueIndex(TrustedUsersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TrustedUsersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(User row) => row.Id;
        }

        public readonly TrustedUsersHandle TrustedUsers;
    }

    public sealed class TrustedUsersCols
    {
        public global::SpacetimeDB.Col<User, int> Id { get; }
        public global::SpacetimeDB.Col<User, string> Identifier { get; }
        public global::SpacetimeDB.Col<User, string> Username { get; }
        public global::SpacetimeDB.Col<User, string> Password { get; }
        public global::SpacetimeDB.Col<User, string> Salt { get; }
        public global::SpacetimeDB.Col<User, int> Iterations { get; }

        public TrustedUsersCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<User, int>(tableName, "id");
            Identifier = new global::SpacetimeDB.Col<User, string>(tableName, "identifier");
            Username = new global::SpacetimeDB.Col<User, string>(tableName, "username");
            Password = new global::SpacetimeDB.Col<User, string>(tableName, "password");
            Salt = new global::SpacetimeDB.Col<User, string>(tableName, "salt");
            Iterations = new global::SpacetimeDB.Col<User, int>(tableName, "iterations");
        }
    }

    public sealed class TrustedUsersIxCols
    {
        public global::SpacetimeDB.IxCol<User, int> Id { get; }

        public TrustedUsersIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<User, int>(tableName, "id");
        }
    }
}
