// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrustedConnectionHandle : RemoteTableHandle<EventContext, TrustedConnection>
        {
            public override string RemoteTableName => "trusted_connection";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(TrustedConnection row) => row.Identity;

                public IdentityUniqueIndex(TrustedConnectionHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal TrustedConnectionHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(TrustedConnection row) => row.Identity;
        }

        public readonly TrustedConnectionHandle TrustedConnection;
    }

    public sealed class TrustedConnectionCols
    {
        public global::SpacetimeDB.Col<TrustedConnection, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<TrustedConnection, string> Subject { get; }
        public global::SpacetimeDB.Col<TrustedConnection, string> Issuer { get; }
        public global::SpacetimeDB.Col<TrustedConnection, SpacetimeDB.Timestamp> ConnectedAt { get; }

        public TrustedConnectionCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<TrustedConnection, SpacetimeDB.Identity>(tableName, "identity");
            Subject = new global::SpacetimeDB.Col<TrustedConnection, string>(tableName, "subject");
            Issuer = new global::SpacetimeDB.Col<TrustedConnection, string>(tableName, "issuer");
            ConnectedAt = new global::SpacetimeDB.Col<TrustedConnection, SpacetimeDB.Timestamp>(tableName, "connected_at");
        }
    }

    public sealed class TrustedConnectionIxCols
    {
        public global::SpacetimeDB.IxCol<TrustedConnection, SpacetimeDB.Identity> Identity { get; }

        public TrustedConnectionIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<TrustedConnection, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
