// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UpdateHistoryHandle : RemoteTableHandle<EventContext, UpdateHistory>
        {
            public override string RemoteTableName => "update_history";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(UpdateHistory row) => row.Id;

                public IdUniqueIndex(UpdateHistoryHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal UpdateHistoryHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(UpdateHistory row) => row.Id;
        }

        public readonly UpdateHistoryHandle UpdateHistory;
    }

    public sealed class UpdateHistoryCols
    {
        public global::SpacetimeDB.Col<UpdateHistory, int> Id { get; }
        public global::SpacetimeDB.Col<UpdateHistory, SpacetimeDB.Timestamp> Date { get; }
        public global::SpacetimeDB.Col<UpdateHistory, string> Version { get; }
        public global::SpacetimeDB.Col<UpdateHistory, int> EventType { get; }

        public UpdateHistoryCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<UpdateHistory, int>(tableName, "id");
            Date = new global::SpacetimeDB.Col<UpdateHistory, SpacetimeDB.Timestamp>(tableName, "date");
            Version = new global::SpacetimeDB.Col<UpdateHistory, string>(tableName, "version");
            EventType = new global::SpacetimeDB.Col<UpdateHistory, int>(tableName, "event_type");
        }
    }

    public sealed class UpdateHistoryIxCols
    {
        public global::SpacetimeDB.IxCol<UpdateHistory, int> Id { get; }

        public UpdateHistoryIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<UpdateHistory, int>(tableName, "id");
        }
    }
}
