// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteCommandHandler(ReducerEventContext ctx, int id);
        public event DeleteCommandHandler? OnDeleteCommand;

        public void DeleteCommand(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteCommand(id));
        }

        public bool InvokeDeleteCommand(ReducerEventContext ctx, Reducer.DeleteCommand args)
        {
            if (OnDeleteCommand == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteCommand(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteCommand : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteCommand(int Id)
            {
                this.Id = Id;
            }

            public DeleteCommand()
            {
            }

            string IReducerArgs.ReducerName => "delete_command";
        }
    }
}
