// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteCustomFormatHandler(ReducerEventContext ctx, int id);
        public event DeleteCustomFormatHandler? OnDeleteCustomFormat;

        public void DeleteCustomFormat(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteCustomFormat(id));
        }

        public bool InvokeDeleteCustomFormat(ReducerEventContext ctx, Reducer.DeleteCustomFormat args)
        {
            if (OnDeleteCustomFormat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteCustomFormat(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteCustomFormat : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteCustomFormat(int Id)
            {
                this.Id = Id;
            }

            public DeleteCustomFormat()
            {
            }

            string IReducerArgs.ReducerName => "delete_custom_format";
        }
    }
}
