// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteSubtitleFileHandler(ReducerEventContext ctx, int id);
        public event DeleteSubtitleFileHandler? OnDeleteSubtitleFile;

        public void DeleteSubtitleFile(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteSubtitleFile(id));
        }

        public bool InvokeDeleteSubtitleFile(ReducerEventContext ctx, Reducer.DeleteSubtitleFile args)
        {
            if (OnDeleteSubtitleFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteSubtitleFile(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteSubtitleFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteSubtitleFile(int Id)
            {
                this.Id = Id;
            }

            public DeleteSubtitleFile()
            {
            }

            string IReducerArgs.ReducerName => "delete_subtitle_file";
        }
    }
}
