// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteQualityProfileHandler(ReducerEventContext ctx, int id);
        public event DeleteQualityProfileHandler? OnDeleteQualityProfile;

        public void DeleteQualityProfile(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteQualityProfile(id));
        }

        public bool InvokeDeleteQualityProfile(ReducerEventContext ctx, Reducer.DeleteQualityProfile args)
        {
            if (OnDeleteQualityProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteQualityProfile(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteQualityProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteQualityProfile(int Id)
            {
                this.Id = Id;
            }

            public DeleteQualityProfile()
            {
            }

            string IReducerArgs.ReducerName => "delete_quality_profile";
        }
    }
}
