// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteDownloadHistoryHandler(ReducerEventContext ctx, int id);
        public event DeleteDownloadHistoryHandler? OnDeleteDownloadHistory;

        public void DeleteDownloadHistory(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteDownloadHistory(id));
        }

        public bool InvokeDeleteDownloadHistory(ReducerEventContext ctx, Reducer.DeleteDownloadHistory args)
        {
            if (OnDeleteDownloadHistory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteDownloadHistory(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteDownloadHistory : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteDownloadHistory(int Id)
            {
                this.Id = Id;
            }

            public DeleteDownloadHistory()
            {
            }

            string IReducerArgs.ReducerName => "delete_download_history";
        }
    }
}
