// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteEpisodeFileHandler(ReducerEventContext ctx, int id);
        public event DeleteEpisodeFileHandler? OnDeleteEpisodeFile;

        public void DeleteEpisodeFile(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteEpisodeFile(id));
        }

        public bool InvokeDeleteEpisodeFile(ReducerEventContext ctx, Reducer.DeleteEpisodeFile args)
        {
            if (OnDeleteEpisodeFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteEpisodeFile(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteEpisodeFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteEpisodeFile(int Id)
            {
                this.Id = Id;
            }

            public DeleteEpisodeFile()
            {
            }

            string IReducerArgs.ReducerName => "delete_episode_file";
        }
    }
}
