// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteAutoTagHandler(ReducerEventContext ctx, int id);
        public event DeleteAutoTagHandler? OnDeleteAutoTag;

        public void DeleteAutoTag(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteAutoTag(id));
        }

        public bool InvokeDeleteAutoTag(ReducerEventContext ctx, Reducer.DeleteAutoTag args)
        {
            if (OnDeleteAutoTag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteAutoTag(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteAutoTag : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteAutoTag(int Id)
            {
                this.Id = Id;
            }

            public DeleteAutoTag()
            {
            }

            string IReducerArgs.ReducerName => "delete_auto_tag";
        }
    }
}
