// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteDownloadClientStatusHandler(ReducerEventContext ctx, int id);
        public event DeleteDownloadClientStatusHandler? OnDeleteDownloadClientStatus;

        public void DeleteDownloadClientStatus(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteDownloadClientStatus(id));
        }

        public bool InvokeDeleteDownloadClientStatus(ReducerEventContext ctx, Reducer.DeleteDownloadClientStatus args)
        {
            if (OnDeleteDownloadClientStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteDownloadClientStatus(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteDownloadClientStatus : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteDownloadClientStatus(int Id)
            {
                this.Id = Id;
            }

            public DeleteDownloadClientStatus()
            {
            }

            string IReducerArgs.ReducerName => "delete_download_client_status";
        }
    }
}
