// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteNamingConfigHandler(ReducerEventContext ctx, int id);
        public event DeleteNamingConfigHandler? OnDeleteNamingConfig;

        public void DeleteNamingConfig(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteNamingConfig(id));
        }

        public bool InvokeDeleteNamingConfig(ReducerEventContext ctx, Reducer.DeleteNamingConfig args)
        {
            if (OnDeleteNamingConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteNamingConfig(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteNamingConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteNamingConfig(int Id)
            {
                this.Id = Id;
            }

            public DeleteNamingConfig()
            {
            }

            string IReducerArgs.ReducerName => "delete_naming_config";
        }
    }
}
