// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteIndexerStatusHandler(ReducerEventContext ctx, int id);
        public event DeleteIndexerStatusHandler? OnDeleteIndexerStatus;

        public void DeleteIndexerStatus(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteIndexerStatus(id));
        }

        public bool InvokeDeleteIndexerStatus(ReducerEventContext ctx, Reducer.DeleteIndexerStatus args)
        {
            if (OnDeleteIndexerStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteIndexerStatus(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteIndexerStatus : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteIndexerStatus(int Id)
            {
                this.Id = Id;
            }

            public DeleteIndexerStatus()
            {
            }

            string IReducerArgs.ReducerName => "delete_indexer_status";
        }
    }
}
