// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteMetadataFileHandler(ReducerEventContext ctx, int id);
        public event DeleteMetadataFileHandler? OnDeleteMetadataFile;

        public void DeleteMetadataFile(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteMetadataFile(id));
        }

        public bool InvokeDeleteMetadataFile(ReducerEventContext ctx, Reducer.DeleteMetadataFile args)
        {
            if (OnDeleteMetadataFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteMetadataFile(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteMetadataFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteMetadataFile(int Id)
            {
                this.Id = Id;
            }

            public DeleteMetadataFile()
            {
            }

            string IReducerArgs.ReducerName => "delete_metadata_file";
        }
    }
}
