// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteImportListExclusionHandler(ReducerEventContext ctx, int id);
        public event DeleteImportListExclusionHandler? OnDeleteImportListExclusion;

        public void DeleteImportListExclusion(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteImportListExclusion(id));
        }

        public bool InvokeDeleteImportListExclusion(ReducerEventContext ctx, Reducer.DeleteImportListExclusion args)
        {
            if (OnDeleteImportListExclusion == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteImportListExclusion(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteImportListExclusion : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteImportListExclusion(int Id)
            {
                this.Id = Id;
            }

            public DeleteImportListExclusion()
            {
            }

            string IReducerArgs.ReducerName => "delete_import_list_exclusion";
        }
    }
}
