// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteUpdateHistoryHandler(ReducerEventContext ctx, int id);
        public event DeleteUpdateHistoryHandler? OnDeleteUpdateHistory;

        public void DeleteUpdateHistory(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteUpdateHistory(id));
        }

        public bool InvokeDeleteUpdateHistory(ReducerEventContext ctx, Reducer.DeleteUpdateHistory args)
        {
            if (OnDeleteUpdateHistory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteUpdateHistory(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteUpdateHistory : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteUpdateHistory(int Id)
            {
                this.Id = Id;
            }

            public DeleteUpdateHistory()
            {
            }

            string IReducerArgs.ReducerName => "delete_update_history";
        }
    }
}
