// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteQualityProfileQualityRankHandler(ReducerEventContext ctx, int id);
        public event DeleteQualityProfileQualityRankHandler? OnDeleteQualityProfileQualityRank;

        public void DeleteQualityProfileQualityRank(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteQualityProfileQualityRank(id));
        }

        public bool InvokeDeleteQualityProfileQualityRank(ReducerEventContext ctx, Reducer.DeleteQualityProfileQualityRank args)
        {
            if (OnDeleteQualityProfileQualityRank == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteQualityProfileQualityRank(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteQualityProfileQualityRank : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteQualityProfileQualityRank(int Id)
            {
                this.Id = Id;
            }

            public DeleteQualityProfileQualityRank()
            {
            }

            string IReducerArgs.ReducerName => "delete_quality_profile_quality_rank";
        }
    }
}
