// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteDelayProfileHandler(ReducerEventContext ctx, int id);
        public event DeleteDelayProfileHandler? OnDeleteDelayProfile;

        public void DeleteDelayProfile(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteDelayProfile(id));
        }

        public bool InvokeDeleteDelayProfile(ReducerEventContext ctx, Reducer.DeleteDelayProfile args)
        {
            if (OnDeleteDelayProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteDelayProfile(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteDelayProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteDelayProfile(int Id)
            {
                this.Id = Id;
            }

            public DeleteDelayProfile()
            {
            }

            string IReducerArgs.ReducerName => "delete_delay_profile";
        }
    }
}
