// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteUserHandler(ReducerEventContext ctx, int id);
        public event DeleteUserHandler? OnDeleteUser;

        public void DeleteUser(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteUser(id));
        }

        public bool InvokeDeleteUser(ReducerEventContext ctx, Reducer.DeleteUser args)
        {
            if (OnDeleteUser == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteUser(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteUser(int Id)
            {
                this.Id = Id;
            }

            public DeleteUser()
            {
            }

            string IReducerArgs.ReducerName => "delete_user";
        }
    }
}
