// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteConfigHandler(ReducerEventContext ctx, int id);
        public event DeleteConfigHandler? OnDeleteConfig;

        public void DeleteConfig(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteConfig(id));
        }

        public bool InvokeDeleteConfig(ReducerEventContext ctx, Reducer.DeleteConfig args)
        {
            if (OnDeleteConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteConfig(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteConfig(int Id)
            {
                this.Id = Id;
            }

            public DeleteConfig()
            {
            }

            string IReducerArgs.ReducerName => "delete_config";
        }
    }
}
