// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteSeriesHandler(ReducerEventContext ctx, int id);
        public event DeleteSeriesHandler? OnDeleteSeries;

        public void DeleteSeries(int id)
        {
            conn.InternalCallReducer(new Reducer.DeleteSeries(id));
        }

        public bool InvokeDeleteSeries(ReducerEventContext ctx, Reducer.DeleteSeries args)
        {
            if (OnDeleteSeries == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteSeries(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteSeries : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;

            public DeleteSeries(int Id)
            {
                this.Id = Id;
            }

            public DeleteSeries()
            {
            }

            string IReducerArgs.ReducerName => "delete_series";
        }
    }
}
