// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertImportListStatusHandler(ReducerEventContext ctx, int providerId, SpacetimeDB.Timestamp? initialFailure, SpacetimeDB.Timestamp? mostRecentFailure, int escalationLevel, SpacetimeDB.Timestamp? disabledTill);
        public event InsertImportListStatusHandler? OnInsertImportListStatus;

        public void InsertImportListStatus(int providerId, SpacetimeDB.Timestamp? initialFailure, SpacetimeDB.Timestamp? mostRecentFailure, int escalationLevel, SpacetimeDB.Timestamp? disabledTill)
        {
            conn.InternalCallReducer(new Reducer.InsertImportListStatus(providerId, initialFailure, mostRecentFailure, escalationLevel, disabledTill));
        }

        public bool InvokeInsertImportListStatus(ReducerEventContext ctx, Reducer.InsertImportListStatus args)
        {
            if (OnInsertImportListStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertImportListStatus(
                ctx,
                args.ProviderId,
                args.InitialFailure,
                args.MostRecentFailure,
                args.EscalationLevel,
                args.DisabledTill
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertImportListStatus : Reducer, IReducerArgs
        {
            [DataMember(Name = "provider_id")]
            public int ProviderId;
            [DataMember(Name = "initial_failure")]
            public SpacetimeDB.Timestamp? InitialFailure;
            [DataMember(Name = "most_recent_failure")]
            public SpacetimeDB.Timestamp? MostRecentFailure;
            [DataMember(Name = "escalation_level")]
            public int EscalationLevel;
            [DataMember(Name = "disabled_till")]
            public SpacetimeDB.Timestamp? DisabledTill;

            public InsertImportListStatus(
                int ProviderId,
                SpacetimeDB.Timestamp? InitialFailure,
                SpacetimeDB.Timestamp? MostRecentFailure,
                int EscalationLevel,
                SpacetimeDB.Timestamp? DisabledTill
            )
            {
                this.ProviderId = ProviderId;
                this.InitialFailure = InitialFailure;
                this.MostRecentFailure = MostRecentFailure;
                this.EscalationLevel = EscalationLevel;
                this.DisabledTill = DisabledTill;
            }

            public InsertImportListStatus()
            {
            }

            string IReducerArgs.ReducerName => "insert_import_list_status";
        }
    }
}
