// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertCustomFormatHandler(ReducerEventContext ctx, string name, bool includeCustomFormatWhenRenaming, string specificationsJson);
        public event InsertCustomFormatHandler? OnInsertCustomFormat;

        public void InsertCustomFormat(string name, bool includeCustomFormatWhenRenaming, string specificationsJson)
        {
            conn.InternalCallReducer(new Reducer.InsertCustomFormat(name, includeCustomFormatWhenRenaming, specificationsJson));
        }

        public bool InvokeInsertCustomFormat(ReducerEventContext ctx, Reducer.InsertCustomFormat args)
        {
            if (OnInsertCustomFormat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertCustomFormat(
                ctx,
                args.Name,
                args.IncludeCustomFormatWhenRenaming,
                args.SpecificationsJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertCustomFormat : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "include_custom_format_when_renaming")]
            public bool IncludeCustomFormatWhenRenaming;
            [DataMember(Name = "specifications_json")]
            public string SpecificationsJson;

            public InsertCustomFormat(
                string Name,
                bool IncludeCustomFormatWhenRenaming,
                string SpecificationsJson
            )
            {
                this.Name = Name;
                this.IncludeCustomFormatWhenRenaming = IncludeCustomFormatWhenRenaming;
                this.SpecificationsJson = SpecificationsJson;
            }

            public InsertCustomFormat()
            {
                this.Name = "";
                this.SpecificationsJson = "";
            }

            string IReducerArgs.ReducerName => "insert_custom_format";
        }
    }
}
