// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertBlocklistHandler(ReducerEventContext ctx, int seriesId, string episodeIdsJson, string sourceTitle, string qualityJson, int qualityId, SpacetimeDB.Timestamp date, SpacetimeDB.Timestamp? publishedDate, long? size, int protocol, string indexer, int indexerFlags, int releaseType, string message, string source, string torrentInfoHash, string languagesJson);
        public event InsertBlocklistHandler? OnInsertBlocklist;

        public void InsertBlocklist(int seriesId, string episodeIdsJson, string sourceTitle, string qualityJson, int qualityId, SpacetimeDB.Timestamp date, SpacetimeDB.Timestamp? publishedDate, long? size, int protocol, string indexer, int indexerFlags, int releaseType, string message, string source, string torrentInfoHash, string languagesJson)
        {
            conn.InternalCallReducer(new Reducer.InsertBlocklist(seriesId, episodeIdsJson, sourceTitle, qualityJson, qualityId, date, publishedDate, size, protocol, indexer, indexerFlags, releaseType, message, source, torrentInfoHash, languagesJson));
        }

        public bool InvokeInsertBlocklist(ReducerEventContext ctx, Reducer.InsertBlocklist args)
        {
            if (OnInsertBlocklist == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertBlocklist(
                ctx,
                args.SeriesId,
                args.EpisodeIdsJson,
                args.SourceTitle,
                args.QualityJson,
                args.QualityId,
                args.Date,
                args.PublishedDate,
                args.Size,
                args.Protocol,
                args.Indexer,
                args.IndexerFlags,
                args.ReleaseType,
                args.Message,
                args.Source,
                args.TorrentInfoHash,
                args.LanguagesJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertBlocklist : Reducer, IReducerArgs
        {
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "episode_ids_json")]
            public string EpisodeIdsJson;
            [DataMember(Name = "source_title")]
            public string SourceTitle;
            [DataMember(Name = "quality_json")]
            public string QualityJson;
            [DataMember(Name = "quality_id")]
            public int QualityId;
            [DataMember(Name = "date")]
            public SpacetimeDB.Timestamp Date;
            [DataMember(Name = "published_date")]
            public SpacetimeDB.Timestamp? PublishedDate;
            [DataMember(Name = "size")]
            public long? Size;
            [DataMember(Name = "protocol")]
            public int Protocol;
            [DataMember(Name = "indexer")]
            public string Indexer;
            [DataMember(Name = "indexer_flags")]
            public int IndexerFlags;
            [DataMember(Name = "release_type")]
            public int ReleaseType;
            [DataMember(Name = "message")]
            public string Message;
            [DataMember(Name = "source")]
            public string Source;
            [DataMember(Name = "torrent_info_hash")]
            public string TorrentInfoHash;
            [DataMember(Name = "languages_json")]
            public string LanguagesJson;

            public InsertBlocklist(
                int SeriesId,
                string EpisodeIdsJson,
                string SourceTitle,
                string QualityJson,
                int QualityId,
                SpacetimeDB.Timestamp Date,
                SpacetimeDB.Timestamp? PublishedDate,
                long? Size,
                int Protocol,
                string Indexer,
                int IndexerFlags,
                int ReleaseType,
                string Message,
                string Source,
                string TorrentInfoHash,
                string LanguagesJson
            )
            {
                this.SeriesId = SeriesId;
                this.EpisodeIdsJson = EpisodeIdsJson;
                this.SourceTitle = SourceTitle;
                this.QualityJson = QualityJson;
                this.QualityId = QualityId;
                this.Date = Date;
                this.PublishedDate = PublishedDate;
                this.Size = Size;
                this.Protocol = Protocol;
                this.Indexer = Indexer;
                this.IndexerFlags = IndexerFlags;
                this.ReleaseType = ReleaseType;
                this.Message = Message;
                this.Source = Source;
                this.TorrentInfoHash = TorrentInfoHash;
                this.LanguagesJson = LanguagesJson;
            }

            public InsertBlocklist()
            {
                this.EpisodeIdsJson = "";
                this.SourceTitle = "";
                this.QualityJson = "";
                this.Indexer = "";
                this.Message = "";
                this.Source = "";
                this.TorrentInfoHash = "";
                this.LanguagesJson = "";
            }

            string IReducerArgs.ReducerName => "insert_blocklist";
        }
    }
}
