// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertQualityProfileQualityRankHandler(ReducerEventContext ctx, int profileId, int qualityId, double score);
        public event InsertQualityProfileQualityRankHandler? OnInsertQualityProfileQualityRank;

        public void InsertQualityProfileQualityRank(int profileId, int qualityId, double score)
        {
            conn.InternalCallReducer(new Reducer.InsertQualityProfileQualityRank(profileId, qualityId, score));
        }

        public bool InvokeInsertQualityProfileQualityRank(ReducerEventContext ctx, Reducer.InsertQualityProfileQualityRank args)
        {
            if (OnInsertQualityProfileQualityRank == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertQualityProfileQualityRank(
                ctx,
                args.ProfileId,
                args.QualityId,
                args.Score
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertQualityProfileQualityRank : Reducer, IReducerArgs
        {
            [DataMember(Name = "profile_id")]
            public int ProfileId;
            [DataMember(Name = "quality_id")]
            public int QualityId;
            [DataMember(Name = "score")]
            public double Score;

            public InsertQualityProfileQualityRank(
                int ProfileId,
                int QualityId,
                double Score
            )
            {
                this.ProfileId = ProfileId;
                this.QualityId = QualityId;
                this.Score = Score;
            }

            public InsertQualityProfileQualityRank()
            {
            }

            string IReducerArgs.ReducerName => "insert_quality_profile_quality_rank";
        }
    }
}
