// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertConfigHandler(ReducerEventContext ctx, string key, string value);
        public event InsertConfigHandler? OnInsertConfig;

        public void InsertConfig(string key, string value)
        {
            conn.InternalCallReducer(new Reducer.InsertConfig(key, value));
        }

        public bool InvokeInsertConfig(ReducerEventContext ctx, Reducer.InsertConfig args)
        {
            if (OnInsertConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertConfig(
                ctx,
                args.Key,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "key")]
            public string Key;
            [DataMember(Name = "value")]
            public string Value;

            public InsertConfig(
                string Key,
                string Value
            )
            {
                this.Key = Key;
                this.Value = Value;
            }

            public InsertConfig()
            {
                this.Key = "";
                this.Value = "";
            }

            string IReducerArgs.ReducerName => "insert_config";
        }
    }
}
