// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertCustomFilterHandler(ReducerEventContext ctx, string type, string label, string filters);
        public event InsertCustomFilterHandler? OnInsertCustomFilter;

        public void InsertCustomFilter(string type, string label, string filters)
        {
            conn.InternalCallReducer(new Reducer.InsertCustomFilter(type, label, filters));
        }

        public bool InvokeInsertCustomFilter(ReducerEventContext ctx, Reducer.InsertCustomFilter args)
        {
            if (OnInsertCustomFilter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertCustomFilter(
                ctx,
                args.Type,
                args.Label,
                args.Filters
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertCustomFilter : Reducer, IReducerArgs
        {
            [DataMember(Name = "type")]
            public string Type;
            [DataMember(Name = "label")]
            public string Label;
            [DataMember(Name = "filters")]
            public string Filters;

            public InsertCustomFilter(
                string Type,
                string Label,
                string Filters
            )
            {
                this.Type = Type;
                this.Label = Label;
                this.Filters = Filters;
            }

            public InsertCustomFilter()
            {
                this.Type = "";
                this.Label = "";
                this.Filters = "";
            }

            string IReducerArgs.ReducerName => "insert_custom_filter";
        }
    }
}
