// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertOtherExtraFileHandler(ReducerEventContext ctx, int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension);
        public event InsertOtherExtraFileHandler? OnInsertOtherExtraFile;

        public void InsertOtherExtraFile(int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension)
        {
            conn.InternalCallReducer(new Reducer.InsertOtherExtraFile(seriesId, episodeFileId, seasonNumber, relativePath, added, lastUpdated, extension));
        }

        public bool InvokeInsertOtherExtraFile(ReducerEventContext ctx, Reducer.InsertOtherExtraFile args)
        {
            if (OnInsertOtherExtraFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertOtherExtraFile(
                ctx,
                args.SeriesId,
                args.EpisodeFileId,
                args.SeasonNumber,
                args.RelativePath,
                args.Added,
                args.LastUpdated,
                args.Extension
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertOtherExtraFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "episode_file_id")]
            public int? EpisodeFileId;
            [DataMember(Name = "season_number")]
            public int? SeasonNumber;
            [DataMember(Name = "relative_path")]
            public string RelativePath;
            [DataMember(Name = "added")]
            public SpacetimeDB.Timestamp Added;
            [DataMember(Name = "last_updated")]
            public SpacetimeDB.Timestamp LastUpdated;
            [DataMember(Name = "extension")]
            public string Extension;

            public InsertOtherExtraFile(
                int SeriesId,
                int? EpisodeFileId,
                int? SeasonNumber,
                string RelativePath,
                SpacetimeDB.Timestamp Added,
                SpacetimeDB.Timestamp LastUpdated,
                string Extension
            )
            {
                this.SeriesId = SeriesId;
                this.EpisodeFileId = EpisodeFileId;
                this.SeasonNumber = SeasonNumber;
                this.RelativePath = RelativePath;
                this.Added = Added;
                this.LastUpdated = LastUpdated;
                this.Extension = Extension;
            }

            public InsertOtherExtraFile()
            {
                this.RelativePath = "";
                this.Extension = "";
            }

            string IReducerArgs.ReducerName => "insert_other_extra_file";
        }
    }
}
