// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertTagHandler(ReducerEventContext ctx, string label);
        public event InsertTagHandler? OnInsertTag;

        public void InsertTag(string label)
        {
            conn.InternalCallReducer(new Reducer.InsertTag(label));
        }

        public bool InvokeInsertTag(ReducerEventContext ctx, Reducer.InsertTag args)
        {
            if (OnInsertTag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertTag(
                ctx,
                args.Label
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertTag : Reducer, IReducerArgs
        {
            [DataMember(Name = "label")]
            public string Label;

            public InsertTag(string Label)
            {
                this.Label = Label;
            }

            public InsertTag()
            {
                this.Label = "";
            }

            string IReducerArgs.ReducerName => "insert_tag";
        }
    }
}
