// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertScheduledTaskHandler(ReducerEventContext ctx, string typeName, int interval, SpacetimeDB.Timestamp lastExecution, int priority, SpacetimeDB.Timestamp lastStartTime);
        public event InsertScheduledTaskHandler? OnInsertScheduledTask;

        public void InsertScheduledTask(string typeName, int interval, SpacetimeDB.Timestamp lastExecution, int priority, SpacetimeDB.Timestamp lastStartTime)
        {
            conn.InternalCallReducer(new Reducer.InsertScheduledTask(typeName, interval, lastExecution, priority, lastStartTime));
        }

        public bool InvokeInsertScheduledTask(ReducerEventContext ctx, Reducer.InsertScheduledTask args)
        {
            if (OnInsertScheduledTask == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertScheduledTask(
                ctx,
                args.TypeName,
                args.Interval,
                args.LastExecution,
                args.Priority,
                args.LastStartTime
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertScheduledTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "type_name")]
            public string TypeName;
            [DataMember(Name = "interval")]
            public int Interval;
            [DataMember(Name = "last_execution")]
            public SpacetimeDB.Timestamp LastExecution;
            [DataMember(Name = "priority")]
            public int Priority;
            [DataMember(Name = "last_start_time")]
            public SpacetimeDB.Timestamp LastStartTime;

            public InsertScheduledTask(
                string TypeName,
                int Interval,
                SpacetimeDB.Timestamp LastExecution,
                int Priority,
                SpacetimeDB.Timestamp LastStartTime
            )
            {
                this.TypeName = TypeName;
                this.Interval = Interval;
                this.LastExecution = LastExecution;
                this.Priority = Priority;
                this.LastStartTime = LastStartTime;
            }

            public InsertScheduledTask()
            {
                this.TypeName = "";
            }

            string IReducerArgs.ReducerName => "insert_scheduled_task";
        }
    }
}
