// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertCustomFormatHandler(ReducerEventContext ctx, int id, string name, bool includeCustomFormatWhenRenaming, string specificationsJson);
        public event MigrateInsertCustomFormatHandler? OnMigrateInsertCustomFormat;

        public void MigrateInsertCustomFormat(int id, string name, bool includeCustomFormatWhenRenaming, string specificationsJson)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertCustomFormat(id, name, includeCustomFormatWhenRenaming, specificationsJson));
        }

        public bool InvokeMigrateInsertCustomFormat(ReducerEventContext ctx, Reducer.MigrateInsertCustomFormat args)
        {
            if (OnMigrateInsertCustomFormat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertCustomFormat(
                ctx,
                args.Id,
                args.Name,
                args.IncludeCustomFormatWhenRenaming,
                args.SpecificationsJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertCustomFormat : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "include_custom_format_when_renaming")]
            public bool IncludeCustomFormatWhenRenaming;
            [DataMember(Name = "specifications_json")]
            public string SpecificationsJson;

            public MigrateInsertCustomFormat(
                int Id,
                string Name,
                bool IncludeCustomFormatWhenRenaming,
                string SpecificationsJson
            )
            {
                this.Id = Id;
                this.Name = Name;
                this.IncludeCustomFormatWhenRenaming = IncludeCustomFormatWhenRenaming;
                this.SpecificationsJson = SpecificationsJson;
            }

            public MigrateInsertCustomFormat()
            {
                this.Name = "";
                this.SpecificationsJson = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_custom_format";
        }
    }
}
