// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertNotificationDefinitionHandler(ReducerEventContext ctx, int id, string name, string implementation, string configContract, string settingsJson, bool enable, string tagsJson, string messageJson);
        public event MigrateInsertNotificationDefinitionHandler? OnMigrateInsertNotificationDefinition;

        public void MigrateInsertNotificationDefinition(int id, string name, string implementation, string configContract, string settingsJson, bool enable, string tagsJson, string messageJson)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertNotificationDefinition(id, name, implementation, configContract, settingsJson, enable, tagsJson, messageJson));
        }

        public bool InvokeMigrateInsertNotificationDefinition(ReducerEventContext ctx, Reducer.MigrateInsertNotificationDefinition args)
        {
            if (OnMigrateInsertNotificationDefinition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertNotificationDefinition(
                ctx,
                args.Id,
                args.Name,
                args.Implementation,
                args.ConfigContract,
                args.SettingsJson,
                args.Enable,
                args.TagsJson,
                args.MessageJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertNotificationDefinition : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "implementation")]
            public string Implementation;
            [DataMember(Name = "config_contract")]
            public string ConfigContract;
            [DataMember(Name = "settings_json")]
            public string SettingsJson;
            [DataMember(Name = "enable")]
            public bool Enable;
            [DataMember(Name = "tags_json")]
            public string TagsJson;
            [DataMember(Name = "message_json")]
            public string MessageJson;

            public MigrateInsertNotificationDefinition(
                int Id,
                string Name,
                string Implementation,
                string ConfigContract,
                string SettingsJson,
                bool Enable,
                string TagsJson,
                string MessageJson
            )
            {
                this.Id = Id;
                this.Name = Name;
                this.Implementation = Implementation;
                this.ConfigContract = ConfigContract;
                this.SettingsJson = SettingsJson;
                this.Enable = Enable;
                this.TagsJson = TagsJson;
                this.MessageJson = MessageJson;
            }

            public MigrateInsertNotificationDefinition()
            {
                this.Name = "";
                this.Implementation = "";
                this.ConfigContract = "";
                this.SettingsJson = "";
                this.TagsJson = "";
                this.MessageJson = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_notification_definition";
        }
    }
}
