// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertMetadataFileHandler(ReducerEventContext ctx, int id, int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension, string hash, string consumer, int type);
        public event MigrateInsertMetadataFileHandler? OnMigrateInsertMetadataFile;

        public void MigrateInsertMetadataFile(int id, int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension, string hash, string consumer, int type)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertMetadataFile(id, seriesId, episodeFileId, seasonNumber, relativePath, added, lastUpdated, extension, hash, consumer, type));
        }

        public bool InvokeMigrateInsertMetadataFile(ReducerEventContext ctx, Reducer.MigrateInsertMetadataFile args)
        {
            if (OnMigrateInsertMetadataFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertMetadataFile(
                ctx,
                args.Id,
                args.SeriesId,
                args.EpisodeFileId,
                args.SeasonNumber,
                args.RelativePath,
                args.Added,
                args.LastUpdated,
                args.Extension,
                args.Hash,
                args.Consumer,
                args.Type
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertMetadataFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "episode_file_id")]
            public int? EpisodeFileId;
            [DataMember(Name = "season_number")]
            public int? SeasonNumber;
            [DataMember(Name = "relative_path")]
            public string RelativePath;
            [DataMember(Name = "added")]
            public SpacetimeDB.Timestamp Added;
            [DataMember(Name = "last_updated")]
            public SpacetimeDB.Timestamp LastUpdated;
            [DataMember(Name = "extension")]
            public string Extension;
            [DataMember(Name = "hash")]
            public string Hash;
            [DataMember(Name = "consumer")]
            public string Consumer;
            [DataMember(Name = "type")]
            public int Type;

            public MigrateInsertMetadataFile(
                int Id,
                int SeriesId,
                int? EpisodeFileId,
                int? SeasonNumber,
                string RelativePath,
                SpacetimeDB.Timestamp Added,
                SpacetimeDB.Timestamp LastUpdated,
                string Extension,
                string Hash,
                string Consumer,
                int Type
            )
            {
                this.Id = Id;
                this.SeriesId = SeriesId;
                this.EpisodeFileId = EpisodeFileId;
                this.SeasonNumber = SeasonNumber;
                this.RelativePath = RelativePath;
                this.Added = Added;
                this.LastUpdated = LastUpdated;
                this.Extension = Extension;
                this.Hash = Hash;
                this.Consumer = Consumer;
                this.Type = Type;
            }

            public MigrateInsertMetadataFile()
            {
                this.RelativePath = "";
                this.Extension = "";
                this.Hash = "";
                this.Consumer = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_metadata_file";
        }
    }
}
