// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertAutoTagHandler(ReducerEventContext ctx, int id, string name, string specificationsJson, bool removeTagsAutomatically, string tagsJson);
        public event MigrateInsertAutoTagHandler? OnMigrateInsertAutoTag;

        public void MigrateInsertAutoTag(int id, string name, string specificationsJson, bool removeTagsAutomatically, string tagsJson)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertAutoTag(id, name, specificationsJson, removeTagsAutomatically, tagsJson));
        }

        public bool InvokeMigrateInsertAutoTag(ReducerEventContext ctx, Reducer.MigrateInsertAutoTag args)
        {
            if (OnMigrateInsertAutoTag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertAutoTag(
                ctx,
                args.Id,
                args.Name,
                args.SpecificationsJson,
                args.RemoveTagsAutomatically,
                args.TagsJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertAutoTag : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "specifications_json")]
            public string SpecificationsJson;
            [DataMember(Name = "remove_tags_automatically")]
            public bool RemoveTagsAutomatically;
            [DataMember(Name = "tags_json")]
            public string TagsJson;

            public MigrateInsertAutoTag(
                int Id,
                string Name,
                string SpecificationsJson,
                bool RemoveTagsAutomatically,
                string TagsJson
            )
            {
                this.Id = Id;
                this.Name = Name;
                this.SpecificationsJson = SpecificationsJson;
                this.RemoveTagsAutomatically = RemoveTagsAutomatically;
                this.TagsJson = TagsJson;
            }

            public MigrateInsertAutoTag()
            {
                this.Name = "";
                this.SpecificationsJson = "";
                this.TagsJson = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_auto_tag";
        }
    }
}
