// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertPendingReleaseHandler(ReducerEventContext ctx, int id, int seriesId, string title, SpacetimeDB.Timestamp added, string parsedEpisodeInfoJson, string releaseJson, int reason, string additionalInfoJson);
        public event MigrateInsertPendingReleaseHandler? OnMigrateInsertPendingRelease;

        public void MigrateInsertPendingRelease(int id, int seriesId, string title, SpacetimeDB.Timestamp added, string parsedEpisodeInfoJson, string releaseJson, int reason, string additionalInfoJson)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertPendingRelease(id, seriesId, title, added, parsedEpisodeInfoJson, releaseJson, reason, additionalInfoJson));
        }

        public bool InvokeMigrateInsertPendingRelease(ReducerEventContext ctx, Reducer.MigrateInsertPendingRelease args)
        {
            if (OnMigrateInsertPendingRelease == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertPendingRelease(
                ctx,
                args.Id,
                args.SeriesId,
                args.Title,
                args.Added,
                args.ParsedEpisodeInfoJson,
                args.ReleaseJson,
                args.Reason,
                args.AdditionalInfoJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertPendingRelease : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "title")]
            public string Title;
            [DataMember(Name = "added")]
            public SpacetimeDB.Timestamp Added;
            [DataMember(Name = "parsed_episode_info_json")]
            public string ParsedEpisodeInfoJson;
            [DataMember(Name = "release_json")]
            public string ReleaseJson;
            [DataMember(Name = "reason")]
            public int Reason;
            [DataMember(Name = "additional_info_json")]
            public string AdditionalInfoJson;

            public MigrateInsertPendingRelease(
                int Id,
                int SeriesId,
                string Title,
                SpacetimeDB.Timestamp Added,
                string ParsedEpisodeInfoJson,
                string ReleaseJson,
                int Reason,
                string AdditionalInfoJson
            )
            {
                this.Id = Id;
                this.SeriesId = SeriesId;
                this.Title = Title;
                this.Added = Added;
                this.ParsedEpisodeInfoJson = ParsedEpisodeInfoJson;
                this.ReleaseJson = ReleaseJson;
                this.Reason = Reason;
                this.AdditionalInfoJson = AdditionalInfoJson;
            }

            public MigrateInsertPendingRelease()
            {
                this.Title = "";
                this.ParsedEpisodeInfoJson = "";
                this.ReleaseJson = "";
                this.AdditionalInfoJson = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_pending_release";
        }
    }
}
