// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateInsertUpdateHistoryHandler(ReducerEventContext ctx, int id, SpacetimeDB.Timestamp date, string version, int eventType);
        public event MigrateInsertUpdateHistoryHandler? OnMigrateInsertUpdateHistory;

        public void MigrateInsertUpdateHistory(int id, SpacetimeDB.Timestamp date, string version, int eventType)
        {
            conn.InternalCallReducer(new Reducer.MigrateInsertUpdateHistory(id, date, version, eventType));
        }

        public bool InvokeMigrateInsertUpdateHistory(ReducerEventContext ctx, Reducer.MigrateInsertUpdateHistory args)
        {
            if (OnMigrateInsertUpdateHistory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateInsertUpdateHistory(
                ctx,
                args.Id,
                args.Date,
                args.Version,
                args.EventType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateInsertUpdateHistory : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "date")]
            public SpacetimeDB.Timestamp Date;
            [DataMember(Name = "version")]
            public string Version;
            [DataMember(Name = "event_type")]
            public int EventType;

            public MigrateInsertUpdateHistory(
                int Id,
                SpacetimeDB.Timestamp Date,
                string Version,
                int EventType
            )
            {
                this.Id = Id;
                this.Date = Date;
                this.Version = Version;
                this.EventType = EventType;
            }

            public MigrateInsertUpdateHistory()
            {
                this.Version = "";
            }

            string IReducerArgs.ReducerName => "migrate_insert_update_history";
        }
    }
}
