// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReplaceQualityProfileQualityRanksHandler(ReducerEventContext ctx, int profileId, System.Collections.Generic.List<SpacetimeDB.Types.QualityRankInput> ranks);
        public event ReplaceQualityProfileQualityRanksHandler? OnReplaceQualityProfileQualityRanks;

        public void ReplaceQualityProfileQualityRanks(int profileId, System.Collections.Generic.List<SpacetimeDB.Types.QualityRankInput> ranks)
        {
            conn.InternalCallReducer(new Reducer.ReplaceQualityProfileQualityRanks(profileId, ranks));
        }

        public bool InvokeReplaceQualityProfileQualityRanks(ReducerEventContext ctx, Reducer.ReplaceQualityProfileQualityRanks args)
        {
            if (OnReplaceQualityProfileQualityRanks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReplaceQualityProfileQualityRanks(
                ctx,
                args.ProfileId,
                args.Ranks
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReplaceQualityProfileQualityRanks : Reducer, IReducerArgs
        {
            [DataMember(Name = "profile_id")]
            public int ProfileId;
            [DataMember(Name = "ranks")]
            public System.Collections.Generic.List<QualityRankInput> Ranks;

            public ReplaceQualityProfileQualityRanks(
                int ProfileId,
                System.Collections.Generic.List<QualityRankInput> Ranks
            )
            {
                this.ProfileId = ProfileId;
                this.Ranks = Ranks;
            }

            public ReplaceQualityProfileQualityRanks()
            {
                this.Ranks = new();
            }

            string IReducerArgs.ReducerName => "replace_quality_profile_quality_ranks";
        }
    }
}
