// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReplaceSeriesTagsHandler(ReducerEventContext ctx, int seriesId, System.Collections.Generic.List<int> tagIds);
        public event ReplaceSeriesTagsHandler? OnReplaceSeriesTags;

        public void ReplaceSeriesTags(int seriesId, System.Collections.Generic.List<int> tagIds)
        {
            conn.InternalCallReducer(new Reducer.ReplaceSeriesTags(seriesId, tagIds));
        }

        public bool InvokeReplaceSeriesTags(ReducerEventContext ctx, Reducer.ReplaceSeriesTags args)
        {
            if (OnReplaceSeriesTags == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReplaceSeriesTags(
                ctx,
                args.SeriesId,
                args.TagIds
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReplaceSeriesTags : Reducer, IReducerArgs
        {
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "tag_ids")]
            public System.Collections.Generic.List<int> TagIds;

            public ReplaceSeriesTags(
                int SeriesId,
                System.Collections.Generic.List<int> TagIds
            )
            {
                this.SeriesId = SeriesId;
                this.TagIds = TagIds;
            }

            public ReplaceSeriesTags()
            {
                this.TagIds = new();
            }

            string IReducerArgs.ReducerName => "replace_series_tags";
        }
    }
}
