// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateNamingConfigHandler(ReducerEventContext ctx, int id, bool renameEpisodes, bool replaceIllegalCharacters, int colonReplacementFormat, string customColonReplacementFormat, int multiEpisodeStyle, string standardEpisodeFormat, string dailyEpisodeFormat, string animeEpisodeFormat, string seriesFolderFormat, string seasonFolderFormat, string specialsFolderFormat);
        public event UpdateNamingConfigHandler? OnUpdateNamingConfig;

        public void UpdateNamingConfig(int id, bool renameEpisodes, bool replaceIllegalCharacters, int colonReplacementFormat, string customColonReplacementFormat, int multiEpisodeStyle, string standardEpisodeFormat, string dailyEpisodeFormat, string animeEpisodeFormat, string seriesFolderFormat, string seasonFolderFormat, string specialsFolderFormat)
        {
            conn.InternalCallReducer(new Reducer.UpdateNamingConfig(id, renameEpisodes, replaceIllegalCharacters, colonReplacementFormat, customColonReplacementFormat, multiEpisodeStyle, standardEpisodeFormat, dailyEpisodeFormat, animeEpisodeFormat, seriesFolderFormat, seasonFolderFormat, specialsFolderFormat));
        }

        public bool InvokeUpdateNamingConfig(ReducerEventContext ctx, Reducer.UpdateNamingConfig args)
        {
            if (OnUpdateNamingConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateNamingConfig(
                ctx,
                args.Id,
                args.RenameEpisodes,
                args.ReplaceIllegalCharacters,
                args.ColonReplacementFormat,
                args.CustomColonReplacementFormat,
                args.MultiEpisodeStyle,
                args.StandardEpisodeFormat,
                args.DailyEpisodeFormat,
                args.AnimeEpisodeFormat,
                args.SeriesFolderFormat,
                args.SeasonFolderFormat,
                args.SpecialsFolderFormat
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateNamingConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "rename_episodes")]
            public bool RenameEpisodes;
            [DataMember(Name = "replace_illegal_characters")]
            public bool ReplaceIllegalCharacters;
            [DataMember(Name = "colon_replacement_format")]
            public int ColonReplacementFormat;
            [DataMember(Name = "custom_colon_replacement_format")]
            public string CustomColonReplacementFormat;
            [DataMember(Name = "multi_episode_style")]
            public int MultiEpisodeStyle;
            [DataMember(Name = "standard_episode_format")]
            public string StandardEpisodeFormat;
            [DataMember(Name = "daily_episode_format")]
            public string DailyEpisodeFormat;
            [DataMember(Name = "anime_episode_format")]
            public string AnimeEpisodeFormat;
            [DataMember(Name = "series_folder_format")]
            public string SeriesFolderFormat;
            [DataMember(Name = "season_folder_format")]
            public string SeasonFolderFormat;
            [DataMember(Name = "specials_folder_format")]
            public string SpecialsFolderFormat;

            public UpdateNamingConfig(
                int Id,
                bool RenameEpisodes,
                bool ReplaceIllegalCharacters,
                int ColonReplacementFormat,
                string CustomColonReplacementFormat,
                int MultiEpisodeStyle,
                string StandardEpisodeFormat,
                string DailyEpisodeFormat,
                string AnimeEpisodeFormat,
                string SeriesFolderFormat,
                string SeasonFolderFormat,
                string SpecialsFolderFormat
            )
            {
                this.Id = Id;
                this.RenameEpisodes = RenameEpisodes;
                this.ReplaceIllegalCharacters = ReplaceIllegalCharacters;
                this.ColonReplacementFormat = ColonReplacementFormat;
                this.CustomColonReplacementFormat = CustomColonReplacementFormat;
                this.MultiEpisodeStyle = MultiEpisodeStyle;
                this.StandardEpisodeFormat = StandardEpisodeFormat;
                this.DailyEpisodeFormat = DailyEpisodeFormat;
                this.AnimeEpisodeFormat = AnimeEpisodeFormat;
                this.SeriesFolderFormat = SeriesFolderFormat;
                this.SeasonFolderFormat = SeasonFolderFormat;
                this.SpecialsFolderFormat = SpecialsFolderFormat;
            }

            public UpdateNamingConfig()
            {
                this.CustomColonReplacementFormat = "";
                this.StandardEpisodeFormat = "";
                this.DailyEpisodeFormat = "";
                this.AnimeEpisodeFormat = "";
                this.SeriesFolderFormat = "";
                this.SeasonFolderFormat = "";
                this.SpecialsFolderFormat = "";
            }

            string IReducerArgs.ReducerName => "update_naming_config";
        }
    }
}
