// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateIndexerStatusHandler(ReducerEventContext ctx, int id, int providerId, SpacetimeDB.Timestamp? initialFailure, SpacetimeDB.Timestamp? mostRecentFailure, int escalationLevel, SpacetimeDB.Timestamp? disabledTill, string lastRssSyncReleaseInfoJson);
        public event UpdateIndexerStatusHandler? OnUpdateIndexerStatus;

        public void UpdateIndexerStatus(int id, int providerId, SpacetimeDB.Timestamp? initialFailure, SpacetimeDB.Timestamp? mostRecentFailure, int escalationLevel, SpacetimeDB.Timestamp? disabledTill, string lastRssSyncReleaseInfoJson)
        {
            conn.InternalCallReducer(new Reducer.UpdateIndexerStatus(id, providerId, initialFailure, mostRecentFailure, escalationLevel, disabledTill, lastRssSyncReleaseInfoJson));
        }

        public bool InvokeUpdateIndexerStatus(ReducerEventContext ctx, Reducer.UpdateIndexerStatus args)
        {
            if (OnUpdateIndexerStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateIndexerStatus(
                ctx,
                args.Id,
                args.ProviderId,
                args.InitialFailure,
                args.MostRecentFailure,
                args.EscalationLevel,
                args.DisabledTill,
                args.LastRssSyncReleaseInfoJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateIndexerStatus : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "provider_id")]
            public int ProviderId;
            [DataMember(Name = "initial_failure")]
            public SpacetimeDB.Timestamp? InitialFailure;
            [DataMember(Name = "most_recent_failure")]
            public SpacetimeDB.Timestamp? MostRecentFailure;
            [DataMember(Name = "escalation_level")]
            public int EscalationLevel;
            [DataMember(Name = "disabled_till")]
            public SpacetimeDB.Timestamp? DisabledTill;
            [DataMember(Name = "last_rss_sync_release_info_json")]
            public string LastRssSyncReleaseInfoJson;

            public UpdateIndexerStatus(
                int Id,
                int ProviderId,
                SpacetimeDB.Timestamp? InitialFailure,
                SpacetimeDB.Timestamp? MostRecentFailure,
                int EscalationLevel,
                SpacetimeDB.Timestamp? DisabledTill,
                string LastRssSyncReleaseInfoJson
            )
            {
                this.Id = Id;
                this.ProviderId = ProviderId;
                this.InitialFailure = InitialFailure;
                this.MostRecentFailure = MostRecentFailure;
                this.EscalationLevel = EscalationLevel;
                this.DisabledTill = DisabledTill;
                this.LastRssSyncReleaseInfoJson = LastRssSyncReleaseInfoJson;
            }

            public UpdateIndexerStatus()
            {
                this.LastRssSyncReleaseInfoJson = "";
            }

            string IReducerArgs.ReducerName => "update_indexer_status";
        }
    }
}
