// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateConfigHandler(ReducerEventContext ctx, int id, string key, string value);
        public event UpdateConfigHandler? OnUpdateConfig;

        public void UpdateConfig(int id, string key, string value)
        {
            conn.InternalCallReducer(new Reducer.UpdateConfig(id, key, value));
        }

        public bool InvokeUpdateConfig(ReducerEventContext ctx, Reducer.UpdateConfig args)
        {
            if (OnUpdateConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateConfig(
                ctx,
                args.Id,
                args.Key,
                args.Value
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "key")]
            public string Key;
            [DataMember(Name = "value")]
            public string Value;

            public UpdateConfig(
                int Id,
                string Key,
                string Value
            )
            {
                this.Id = Id;
                this.Key = Key;
                this.Value = Value;
            }

            public UpdateConfig()
            {
                this.Key = "";
                this.Value = "";
            }

            string IReducerArgs.ReducerName => "update_config";
        }
    }
}
