// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateRootFolderHandler(ReducerEventContext ctx, int id, string path);
        public event UpdateRootFolderHandler? OnUpdateRootFolder;

        public void UpdateRootFolder(int id, string path)
        {
            conn.InternalCallReducer(new Reducer.UpdateRootFolder(id, path));
        }

        public bool InvokeUpdateRootFolder(ReducerEventContext ctx, Reducer.UpdateRootFolder args)
        {
            if (OnUpdateRootFolder == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateRootFolder(
                ctx,
                args.Id,
                args.Path
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateRootFolder : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "path")]
            public string Path;

            public UpdateRootFolder(
                int Id,
                string Path
            )
            {
                this.Id = Id;
                this.Path = Path;
            }

            public UpdateRootFolder()
            {
                this.Path = "";
            }

            string IReducerArgs.ReducerName => "update_root_folder";
        }
    }
}
