// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateTagHandler(ReducerEventContext ctx, int id, string label);
        public event UpdateTagHandler? OnUpdateTag;

        public void UpdateTag(int id, string label)
        {
            conn.InternalCallReducer(new Reducer.UpdateTag(id, label));
        }

        public bool InvokeUpdateTag(ReducerEventContext ctx, Reducer.UpdateTag args)
        {
            if (OnUpdateTag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateTag(
                ctx,
                args.Id,
                args.Label
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateTag : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "label")]
            public string Label;

            public UpdateTag(
                int Id,
                string Label
            )
            {
                this.Id = Id;
                this.Label = Label;
            }

            public UpdateTag()
            {
                this.Label = "";
            }

            string IReducerArgs.ReducerName => "update_tag";
        }
    }
}
