// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateQualityProfileQualityRankHandler(ReducerEventContext ctx, int id, int profileId, int qualityId, double score);
        public event UpdateQualityProfileQualityRankHandler? OnUpdateQualityProfileQualityRank;

        public void UpdateQualityProfileQualityRank(int id, int profileId, int qualityId, double score)
        {
            conn.InternalCallReducer(new Reducer.UpdateQualityProfileQualityRank(id, profileId, qualityId, score));
        }

        public bool InvokeUpdateQualityProfileQualityRank(ReducerEventContext ctx, Reducer.UpdateQualityProfileQualityRank args)
        {
            if (OnUpdateQualityProfileQualityRank == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateQualityProfileQualityRank(
                ctx,
                args.Id,
                args.ProfileId,
                args.QualityId,
                args.Score
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateQualityProfileQualityRank : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "profile_id")]
            public int ProfileId;
            [DataMember(Name = "quality_id")]
            public int QualityId;
            [DataMember(Name = "score")]
            public double Score;

            public UpdateQualityProfileQualityRank(
                int Id,
                int ProfileId,
                int QualityId,
                double Score
            )
            {
                this.Id = Id;
                this.ProfileId = ProfileId;
                this.QualityId = QualityId;
                this.Score = Score;
            }

            public UpdateQualityProfileQualityRank()
            {
            }

            string IReducerArgs.ReducerName => "update_quality_profile_quality_rank";
        }
    }
}
