// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateEpisodeHistoryHandler(ReducerEventContext ctx, int id, int episodeId, int seriesId, string sourceTitle, string qualityJson, int qualityId, SpacetimeDB.Timestamp date, int eventType, string dataJson, string languagesJson, string downloadId);
        public event UpdateEpisodeHistoryHandler? OnUpdateEpisodeHistory;

        public void UpdateEpisodeHistory(int id, int episodeId, int seriesId, string sourceTitle, string qualityJson, int qualityId, SpacetimeDB.Timestamp date, int eventType, string dataJson, string languagesJson, string downloadId)
        {
            conn.InternalCallReducer(new Reducer.UpdateEpisodeHistory(id, episodeId, seriesId, sourceTitle, qualityJson, qualityId, date, eventType, dataJson, languagesJson, downloadId));
        }

        public bool InvokeUpdateEpisodeHistory(ReducerEventContext ctx, Reducer.UpdateEpisodeHistory args)
        {
            if (OnUpdateEpisodeHistory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateEpisodeHistory(
                ctx,
                args.Id,
                args.EpisodeId,
                args.SeriesId,
                args.SourceTitle,
                args.QualityJson,
                args.QualityId,
                args.Date,
                args.EventType,
                args.DataJson,
                args.LanguagesJson,
                args.DownloadId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateEpisodeHistory : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "episode_id")]
            public int EpisodeId;
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "source_title")]
            public string SourceTitle;
            [DataMember(Name = "quality_json")]
            public string QualityJson;
            [DataMember(Name = "quality_id")]
            public int QualityId;
            [DataMember(Name = "date")]
            public SpacetimeDB.Timestamp Date;
            [DataMember(Name = "event_type")]
            public int EventType;
            [DataMember(Name = "data_json")]
            public string DataJson;
            [DataMember(Name = "languages_json")]
            public string LanguagesJson;
            [DataMember(Name = "download_id")]
            public string DownloadId;

            public UpdateEpisodeHistory(
                int Id,
                int EpisodeId,
                int SeriesId,
                string SourceTitle,
                string QualityJson,
                int QualityId,
                SpacetimeDB.Timestamp Date,
                int EventType,
                string DataJson,
                string LanguagesJson,
                string DownloadId
            )
            {
                this.Id = Id;
                this.EpisodeId = EpisodeId;
                this.SeriesId = SeriesId;
                this.SourceTitle = SourceTitle;
                this.QualityJson = QualityJson;
                this.QualityId = QualityId;
                this.Date = Date;
                this.EventType = EventType;
                this.DataJson = DataJson;
                this.LanguagesJson = LanguagesJson;
                this.DownloadId = DownloadId;
            }

            public UpdateEpisodeHistory()
            {
                this.SourceTitle = "";
                this.QualityJson = "";
                this.DataJson = "";
                this.LanguagesJson = "";
                this.DownloadId = "";
            }

            string IReducerArgs.ReducerName => "update_episode_history";
        }
    }
}
