// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateQualityProfileHandler(ReducerEventContext ctx, int id, string name, bool upgradeAllowed, int cutoff, int minFormatScore, int cutoffFormatScore, int minUpgradeFormatScore, string formatItemsJson, string itemsJson);
        public event UpdateQualityProfileHandler? OnUpdateQualityProfile;

        public void UpdateQualityProfile(int id, string name, bool upgradeAllowed, int cutoff, int minFormatScore, int cutoffFormatScore, int minUpgradeFormatScore, string formatItemsJson, string itemsJson)
        {
            conn.InternalCallReducer(new Reducer.UpdateQualityProfile(id, name, upgradeAllowed, cutoff, minFormatScore, cutoffFormatScore, minUpgradeFormatScore, formatItemsJson, itemsJson));
        }

        public bool InvokeUpdateQualityProfile(ReducerEventContext ctx, Reducer.UpdateQualityProfile args)
        {
            if (OnUpdateQualityProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateQualityProfile(
                ctx,
                args.Id,
                args.Name,
                args.UpgradeAllowed,
                args.Cutoff,
                args.MinFormatScore,
                args.CutoffFormatScore,
                args.MinUpgradeFormatScore,
                args.FormatItemsJson,
                args.ItemsJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateQualityProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "upgrade_allowed")]
            public bool UpgradeAllowed;
            [DataMember(Name = "cutoff")]
            public int Cutoff;
            [DataMember(Name = "min_format_score")]
            public int MinFormatScore;
            [DataMember(Name = "cutoff_format_score")]
            public int CutoffFormatScore;
            [DataMember(Name = "min_upgrade_format_score")]
            public int MinUpgradeFormatScore;
            [DataMember(Name = "format_items_json")]
            public string FormatItemsJson;
            [DataMember(Name = "items_json")]
            public string ItemsJson;

            public UpdateQualityProfile(
                int Id,
                string Name,
                bool UpgradeAllowed,
                int Cutoff,
                int MinFormatScore,
                int CutoffFormatScore,
                int MinUpgradeFormatScore,
                string FormatItemsJson,
                string ItemsJson
            )
            {
                this.Id = Id;
                this.Name = Name;
                this.UpgradeAllowed = UpgradeAllowed;
                this.Cutoff = Cutoff;
                this.MinFormatScore = MinFormatScore;
                this.CutoffFormatScore = CutoffFormatScore;
                this.MinUpgradeFormatScore = MinUpgradeFormatScore;
                this.FormatItemsJson = FormatItemsJson;
                this.ItemsJson = ItemsJson;
            }

            public UpdateQualityProfile()
            {
                this.Name = "";
                this.FormatItemsJson = "";
                this.ItemsJson = "";
            }

            string IReducerArgs.ReducerName => "update_quality_profile";
        }
    }
}
