// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateCustomFilterHandler(ReducerEventContext ctx, int id, string type, string label, string filters);
        public event UpdateCustomFilterHandler? OnUpdateCustomFilter;

        public void UpdateCustomFilter(int id, string type, string label, string filters)
        {
            conn.InternalCallReducer(new Reducer.UpdateCustomFilter(id, type, label, filters));
        }

        public bool InvokeUpdateCustomFilter(ReducerEventContext ctx, Reducer.UpdateCustomFilter args)
        {
            if (OnUpdateCustomFilter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateCustomFilter(
                ctx,
                args.Id,
                args.Type,
                args.Label,
                args.Filters
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateCustomFilter : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "type")]
            public string Type;
            [DataMember(Name = "label")]
            public string Label;
            [DataMember(Name = "filters")]
            public string Filters;

            public UpdateCustomFilter(
                int Id,
                string Type,
                string Label,
                string Filters
            )
            {
                this.Id = Id;
                this.Type = Type;
                this.Label = Label;
                this.Filters = Filters;
            }

            public UpdateCustomFilter()
            {
                this.Type = "";
                this.Label = "";
                this.Filters = "";
            }

            string IReducerArgs.ReducerName => "update_custom_filter";
        }
    }
}
