// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateRemotePathMappingHandler(ReducerEventContext ctx, int id, string host, string remotePath, string localPath);
        public event UpdateRemotePathMappingHandler? OnUpdateRemotePathMapping;

        public void UpdateRemotePathMapping(int id, string host, string remotePath, string localPath)
        {
            conn.InternalCallReducer(new Reducer.UpdateRemotePathMapping(id, host, remotePath, localPath));
        }

        public bool InvokeUpdateRemotePathMapping(ReducerEventContext ctx, Reducer.UpdateRemotePathMapping args)
        {
            if (OnUpdateRemotePathMapping == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateRemotePathMapping(
                ctx,
                args.Id,
                args.Host,
                args.RemotePath,
                args.LocalPath
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateRemotePathMapping : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "host")]
            public string Host;
            [DataMember(Name = "remote_path")]
            public string RemotePath;
            [DataMember(Name = "local_path")]
            public string LocalPath;

            public UpdateRemotePathMapping(
                int Id,
                string Host,
                string RemotePath,
                string LocalPath
            )
            {
                this.Id = Id;
                this.Host = Host;
                this.RemotePath = RemotePath;
                this.LocalPath = LocalPath;
            }

            public UpdateRemotePathMapping()
            {
                this.Host = "";
                this.RemotePath = "";
                this.LocalPath = "";
            }

            string IReducerArgs.ReducerName => "update_remote_path_mapping";
        }
    }
}
