// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateUserHandler(ReducerEventContext ctx, int id, string identifier, string username, string password, string salt, int iterations);
        public event UpdateUserHandler? OnUpdateUser;

        public void UpdateUser(int id, string identifier, string username, string password, string salt, int iterations)
        {
            conn.InternalCallReducer(new Reducer.UpdateUser(id, identifier, username, password, salt, iterations));
        }

        public bool InvokeUpdateUser(ReducerEventContext ctx, Reducer.UpdateUser args)
        {
            if (OnUpdateUser == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateUser(
                ctx,
                args.Id,
                args.Identifier,
                args.Username,
                args.Password,
                args.Salt,
                args.Iterations
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "identifier")]
            public string Identifier;
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;
            [DataMember(Name = "salt")]
            public string Salt;
            [DataMember(Name = "iterations")]
            public int Iterations;

            public UpdateUser(
                int Id,
                string Identifier,
                string Username,
                string Password,
                string Salt,
                int Iterations
            )
            {
                this.Id = Id;
                this.Identifier = Identifier;
                this.Username = Username;
                this.Password = Password;
                this.Salt = Salt;
                this.Iterations = Iterations;
            }

            public UpdateUser()
            {
                this.Identifier = "";
                this.Username = "";
                this.Password = "";
                this.Salt = "";
            }

            string IReducerArgs.ReducerName => "update_user";
        }
    }
}
