// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateImportListExclusionHandler(ReducerEventContext ctx, int id, int tvdbId, string title);
        public event UpdateImportListExclusionHandler? OnUpdateImportListExclusion;

        public void UpdateImportListExclusion(int id, int tvdbId, string title)
        {
            conn.InternalCallReducer(new Reducer.UpdateImportListExclusion(id, tvdbId, title));
        }

        public bool InvokeUpdateImportListExclusion(ReducerEventContext ctx, Reducer.UpdateImportListExclusion args)
        {
            if (OnUpdateImportListExclusion == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateImportListExclusion(
                ctx,
                args.Id,
                args.TvdbId,
                args.Title
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateImportListExclusion : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "tvdb_id")]
            public int TvdbId;
            [DataMember(Name = "title")]
            public string Title;

            public UpdateImportListExclusion(
                int Id,
                int TvdbId,
                string Title
            )
            {
                this.Id = Id;
                this.TvdbId = TvdbId;
                this.Title = Title;
            }

            public UpdateImportListExclusion()
            {
                this.Title = "";
            }

            string IReducerArgs.ReducerName => "update_import_list_exclusion";
        }
    }
}
