// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateImportListItemHandler(ReducerEventContext ctx, int id, int importListId, string title, int year, int tvdbId, int tmdbId, string imdbId, int malId, int aniListId, SpacetimeDB.Timestamp releaseDate);
        public event UpdateImportListItemHandler? OnUpdateImportListItem;

        public void UpdateImportListItem(int id, int importListId, string title, int year, int tvdbId, int tmdbId, string imdbId, int malId, int aniListId, SpacetimeDB.Timestamp releaseDate)
        {
            conn.InternalCallReducer(new Reducer.UpdateImportListItem(id, importListId, title, year, tvdbId, tmdbId, imdbId, malId, aniListId, releaseDate));
        }

        public bool InvokeUpdateImportListItem(ReducerEventContext ctx, Reducer.UpdateImportListItem args)
        {
            if (OnUpdateImportListItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateImportListItem(
                ctx,
                args.Id,
                args.ImportListId,
                args.Title,
                args.Year,
                args.TvdbId,
                args.TmdbId,
                args.ImdbId,
                args.MalId,
                args.AniListId,
                args.ReleaseDate
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateImportListItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "import_list_id")]
            public int ImportListId;
            [DataMember(Name = "title")]
            public string Title;
            [DataMember(Name = "year")]
            public int Year;
            [DataMember(Name = "tvdb_id")]
            public int TvdbId;
            [DataMember(Name = "tmdb_id")]
            public int TmdbId;
            [DataMember(Name = "imdb_id")]
            public string ImdbId;
            [DataMember(Name = "mal_id")]
            public int MalId;
            [DataMember(Name = "ani_list_id")]
            public int AniListId;
            [DataMember(Name = "release_date")]
            public SpacetimeDB.Timestamp ReleaseDate;

            public UpdateImportListItem(
                int Id,
                int ImportListId,
                string Title,
                int Year,
                int TvdbId,
                int TmdbId,
                string ImdbId,
                int MalId,
                int AniListId,
                SpacetimeDB.Timestamp ReleaseDate
            )
            {
                this.Id = Id;
                this.ImportListId = ImportListId;
                this.Title = Title;
                this.Year = Year;
                this.TvdbId = TvdbId;
                this.TmdbId = TmdbId;
                this.ImdbId = ImdbId;
                this.MalId = MalId;
                this.AniListId = AniListId;
                this.ReleaseDate = ReleaseDate;
            }

            public UpdateImportListItem()
            {
                this.Title = "";
                this.ImdbId = "";
            }

            string IReducerArgs.ReducerName => "update_import_list_item";
        }
    }
}
