// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateSubtitleFileHandler(ReducerEventContext ctx, int id, int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension, string languageJson, int copy, string languageTagsJson, string title);
        public event UpdateSubtitleFileHandler? OnUpdateSubtitleFile;

        public void UpdateSubtitleFile(int id, int seriesId, int? episodeFileId, int? seasonNumber, string relativePath, SpacetimeDB.Timestamp added, SpacetimeDB.Timestamp lastUpdated, string extension, string languageJson, int copy, string languageTagsJson, string title)
        {
            conn.InternalCallReducer(new Reducer.UpdateSubtitleFile(id, seriesId, episodeFileId, seasonNumber, relativePath, added, lastUpdated, extension, languageJson, copy, languageTagsJson, title));
        }

        public bool InvokeUpdateSubtitleFile(ReducerEventContext ctx, Reducer.UpdateSubtitleFile args)
        {
            if (OnUpdateSubtitleFile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateSubtitleFile(
                ctx,
                args.Id,
                args.SeriesId,
                args.EpisodeFileId,
                args.SeasonNumber,
                args.RelativePath,
                args.Added,
                args.LastUpdated,
                args.Extension,
                args.LanguageJson,
                args.Copy,
                args.LanguageTagsJson,
                args.Title
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateSubtitleFile : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "series_id")]
            public int SeriesId;
            [DataMember(Name = "episode_file_id")]
            public int? EpisodeFileId;
            [DataMember(Name = "season_number")]
            public int? SeasonNumber;
            [DataMember(Name = "relative_path")]
            public string RelativePath;
            [DataMember(Name = "added")]
            public SpacetimeDB.Timestamp Added;
            [DataMember(Name = "last_updated")]
            public SpacetimeDB.Timestamp LastUpdated;
            [DataMember(Name = "extension")]
            public string Extension;
            [DataMember(Name = "language_json")]
            public string LanguageJson;
            [DataMember(Name = "copy")]
            public int Copy;
            [DataMember(Name = "language_tags_json")]
            public string LanguageTagsJson;
            [DataMember(Name = "title")]
            public string Title;

            public UpdateSubtitleFile(
                int Id,
                int SeriesId,
                int? EpisodeFileId,
                int? SeasonNumber,
                string RelativePath,
                SpacetimeDB.Timestamp Added,
                SpacetimeDB.Timestamp LastUpdated,
                string Extension,
                string LanguageJson,
                int Copy,
                string LanguageTagsJson,
                string Title
            )
            {
                this.Id = Id;
                this.SeriesId = SeriesId;
                this.EpisodeFileId = EpisodeFileId;
                this.SeasonNumber = SeasonNumber;
                this.RelativePath = RelativePath;
                this.Added = Added;
                this.LastUpdated = LastUpdated;
                this.Extension = Extension;
                this.LanguageJson = LanguageJson;
                this.Copy = Copy;
                this.LanguageTagsJson = LanguageTagsJson;
                this.Title = Title;
            }

            public UpdateSubtitleFile()
            {
                this.RelativePath = "";
                this.Extension = "";
                this.LanguageJson = "";
                this.LanguageTagsJson = "";
                this.Title = "";
            }

            string IReducerArgs.ReducerName => "update_subtitle_file";
        }
    }
}
