// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateQualityDefinitionHandler(ReducerEventContext ctx, int id, string qualityJson, string title);
        public event UpdateQualityDefinitionHandler? OnUpdateQualityDefinition;

        public void UpdateQualityDefinition(int id, string qualityJson, string title)
        {
            conn.InternalCallReducer(new Reducer.UpdateQualityDefinition(id, qualityJson, title));
        }

        public bool InvokeUpdateQualityDefinition(ReducerEventContext ctx, Reducer.UpdateQualityDefinition args)
        {
            if (OnUpdateQualityDefinition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateQualityDefinition(
                ctx,
                args.Id,
                args.QualityJson,
                args.Title
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateQualityDefinition : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "quality_json")]
            public string QualityJson;
            [DataMember(Name = "title")]
            public string Title;

            public UpdateQualityDefinition(
                int Id,
                string QualityJson,
                string Title
            )
            {
                this.Id = Id;
                this.QualityJson = QualityJson;
                this.Title = Title;
            }

            public UpdateQualityDefinition()
            {
                this.QualityJson = "";
                this.Title = "";
            }

            string IReducerArgs.ReducerName => "update_quality_definition";
        }
    }
}
