// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed partial class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(AutoTag = new(conn));
            AddTable(Blocklist = new(conn));
            AddTable(Command = new(conn));
            AddTable(CustomFilter = new(conn));
            AddTable(CustomFormat = new(conn));
            AddTable(DelayProfile = new(conn));
            AddTable(DownloadClientDefinition = new(conn));
            AddTable(DownloadClientStatus = new(conn));
            AddTable(DownloadHistory = new(conn));
            AddTable(Episode = new(conn));
            AddTable(EpisodeFile = new(conn));
            AddTable(EpisodeHistory = new(conn));
            AddTable(ImportListDefinition = new(conn));
            AddTable(ImportListExclusion = new(conn));
            AddTable(ImportListItem = new(conn));
            AddTable(ImportListStatus = new(conn));
            AddTable(IndexerDefinition = new(conn));
            AddTable(IndexerStatus = new(conn));
            AddTable(MetadataDefinition = new(conn));
            AddTable(MetadataFile = new(conn));
            AddTable(NamingConfig = new(conn));
            AddTable(NotificationDefinition = new(conn));
            AddTable(NotificationStatus = new(conn));
            AddTable(OtherExtraFile = new(conn));
            AddTable(PendingRelease = new(conn));
            AddTable(QualityDefinition = new(conn));
            AddTable(QualityProfile = new(conn));
            AddTable(QualityProfileQualityRank = new(conn));
            AddTable(ReleaseProfile = new(conn));
            AddTable(RemotePathMapping = new(conn));
            AddTable(RootFolder = new(conn));
            AddTable(SceneMapping = new(conn));
            AddTable(ScheduledTask = new(conn));
            AddTable(Series = new(conn));
            AddTable(SeriesTag = new(conn));
            AddTable(SubtitleFile = new(conn));
            AddTable(Tag = new(conn));
            AddTable(TrustedConfigs = new(conn));
            AddTable(TrustedConnection = new(conn));
            AddTable(TrustedUsers = new(conn));
            AddTable(UpdateHistory = new(conn));
        }
    }


        public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures> {
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
        }

        public sealed class EventContext : IEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// The event that caused this callback to run.
            /// </summary>
            public readonly Event<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal EventContext(DbConnection conn, Event<Reducer> Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The reducer event that caused this callback to run.
            /// </summary>
            public readonly ReducerEvent<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
            {
                this.conn = conn;
                Event = reducerEvent;
            }
        }

        public sealed class ErrorContext : IErrorContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The <c>Exception</c> that caused this error callback to be run.
            /// </summary>
            public readonly Exception Event;
            Exception IErrorContext.Event {
                get {
                    return Event;
                }
            }

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ErrorContext(DbConnection conn, Exception error)
            {
                this.conn = conn;
                Event = error;
            }
        }

        public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal SubscriptionEventContext(DbConnection conn)
            {
                this.conn = conn;
            }
        }

        public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The procedure event that caused this callback to run.
            /// </summary>
            public readonly ProcedureEvent Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        /// <summary>
        /// Builder-pattern constructor for subscription queries.
        /// </summary>
        public sealed class SubscriptionBuilder
        {
            private readonly IDbConnection conn;

            private event Action<SubscriptionEventContext>? Applied;
            private event Action<ErrorContext, Exception>? Error;

            /// <summary>
            /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
            /// </summary>
            public SubscriptionBuilder(IDbConnection conn)
            {
                this.conn = conn;
            }

            /// <summary>
            /// Register a callback to run when the subscription is applied.
            /// </summary>
            public SubscriptionBuilder OnApplied(
                Action<SubscriptionEventContext> callback
            )
            {
                Applied += callback;
                return this;
            }

            /// <summary>
            /// Register a callback to run when the subscription fails.
            ///
            /// Note that this callback may run either when attempting to apply the subscription,
            /// in which case <c>Self::on_applied</c> will never run,
            /// or later during the subscription's lifetime if the module's interface changes,
            /// in which case <c>Self::on_applied</c> may have already run.
            /// </summary>
            public SubscriptionBuilder OnError(
                Action<ErrorContext, Exception> callback
            )
            {
                Error += callback;
                return this;
            }
        
            /// <summary>
            /// Add a typed query to this subscription.
            ///
            /// This is the entry point for building subscriptions without writing SQL by hand.
            /// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
            /// </summary>
            public TypedSubscriptionBuilder AddQuery<TRow>(
                Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
            )
            {
                var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
                return typed.AddQuery(build);
            }

            /// <summary>
            /// Subscribe to the following SQL queries.
            ///
            /// This method returns immediately, with the data not yet added to the DbConnection.
            /// The provided callbacks will be invoked once the data is returned from the remote server.
            /// Data from all the provided queries will be returned at the same time.
            ///
            /// See the SpacetimeDB SQL docs for more information on SQL syntax:
            /// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
            /// </summary>
            public SubscriptionHandle Subscribe(
                string[] querySqls
            ) => new(conn, Applied, Error, querySqls);

            /// <summary>
            /// Subscribe to all rows from all tables.
            ///
            /// This method is intended as a convenience
            /// for applications where client-side memory use and network bandwidth are not concerns.
            /// Applications where these resources are a constraint
            /// should register more precise queries via <c>Self.Subscribe</c>
            /// in order to replicate only the subset of data which the client needs to function.
            ///
            /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
            /// A connection may either <c>Self.Subscribe</c> to particular queries,
            /// or <c>Self.SubscribeToAllTables</c>, but not both.
            /// Attempting to call <c>Self.Subscribe</c>
            /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
            /// or vice versa, may misbehave in any number of ways,
            /// including dropping subscriptions, corrupting the client cache, or panicking.
            /// </summary>
            public SubscriptionHandle SubscribeToAllTables() =>
                new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
        }

        public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext> {
            /// <summary>
            /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
            /// </summary>
            public SubscriptionHandle(
                IDbConnection conn,
                Action<SubscriptionEventContext>? onApplied,
                Action<ErrorContext, Exception>? onError,
                string[] querySqls
            ) : base(conn, onApplied, onError, querySqls)
            { }
        }

    public sealed class QueryBuilder
    {
        public From From { get; } = new();

        internal static string[] AllTablesSqlQueries() => new string[]
        {
            new QueryBuilder().From.AutoTag().ToSql(),
            new QueryBuilder().From.Blocklist().ToSql(),
            new QueryBuilder().From.Command().ToSql(),
            new QueryBuilder().From.CustomFilter().ToSql(),
            new QueryBuilder().From.CustomFormat().ToSql(),
            new QueryBuilder().From.DelayProfile().ToSql(),
            new QueryBuilder().From.DownloadClientDefinition().ToSql(),
            new QueryBuilder().From.DownloadClientStatus().ToSql(),
            new QueryBuilder().From.DownloadHistory().ToSql(),
            new QueryBuilder().From.Episode().ToSql(),
            new QueryBuilder().From.EpisodeFile().ToSql(),
            new QueryBuilder().From.EpisodeHistory().ToSql(),
            new QueryBuilder().From.ImportListDefinition().ToSql(),
            new QueryBuilder().From.ImportListExclusion().ToSql(),
            new QueryBuilder().From.ImportListItem().ToSql(),
            new QueryBuilder().From.ImportListStatus().ToSql(),
            new QueryBuilder().From.IndexerDefinition().ToSql(),
            new QueryBuilder().From.IndexerStatus().ToSql(),
            new QueryBuilder().From.MetadataDefinition().ToSql(),
            new QueryBuilder().From.MetadataFile().ToSql(),
            new QueryBuilder().From.NamingConfig().ToSql(),
            new QueryBuilder().From.NotificationDefinition().ToSql(),
            new QueryBuilder().From.NotificationStatus().ToSql(),
            new QueryBuilder().From.OtherExtraFile().ToSql(),
            new QueryBuilder().From.PendingRelease().ToSql(),
            new QueryBuilder().From.QualityDefinition().ToSql(),
            new QueryBuilder().From.QualityProfile().ToSql(),
            new QueryBuilder().From.QualityProfileQualityRank().ToSql(),
            new QueryBuilder().From.ReleaseProfile().ToSql(),
            new QueryBuilder().From.RemotePathMapping().ToSql(),
            new QueryBuilder().From.RootFolder().ToSql(),
            new QueryBuilder().From.SceneMapping().ToSql(),
            new QueryBuilder().From.ScheduledTask().ToSql(),
            new QueryBuilder().From.Series().ToSql(),
            new QueryBuilder().From.SeriesTag().ToSql(),
            new QueryBuilder().From.SubtitleFile().ToSql(),
            new QueryBuilder().From.Tag().ToSql(),
            new QueryBuilder().From.TrustedConfigs().ToSql(),
            new QueryBuilder().From.TrustedConnection().ToSql(),
            new QueryBuilder().From.TrustedUsers().ToSql(),
            new QueryBuilder().From.UpdateHistory().ToSql(),
        }
        ;
    }

    public sealed class From
    {
        public global::SpacetimeDB.Table<AutoTag, AutoTagCols, AutoTagIxCols> AutoTag() => new("auto_tag", new AutoTagCols("auto_tag"), new AutoTagIxCols("auto_tag"));
        public global::SpacetimeDB.Table<Blocklist, BlocklistCols, BlocklistIxCols> Blocklist() => new("blocklist", new BlocklistCols("blocklist"), new BlocklistIxCols("blocklist"));
        public global::SpacetimeDB.Table<CommandRow, CommandCols, CommandIxCols> Command() => new("command", new CommandCols("command"), new CommandIxCols("command"));
        public global::SpacetimeDB.Table<CustomFilter, CustomFilterCols, CustomFilterIxCols> CustomFilter() => new("custom_filter", new CustomFilterCols("custom_filter"), new CustomFilterIxCols("custom_filter"));
        public global::SpacetimeDB.Table<CustomFormat, CustomFormatCols, CustomFormatIxCols> CustomFormat() => new("custom_format", new CustomFormatCols("custom_format"), new CustomFormatIxCols("custom_format"));
        public global::SpacetimeDB.Table<DelayProfile, DelayProfileCols, DelayProfileIxCols> DelayProfile() => new("delay_profile", new DelayProfileCols("delay_profile"), new DelayProfileIxCols("delay_profile"));
        public global::SpacetimeDB.Table<DownloadClientDefinition, DownloadClientDefinitionCols, DownloadClientDefinitionIxCols> DownloadClientDefinition() => new("download_client_definition", new DownloadClientDefinitionCols("download_client_definition"), new DownloadClientDefinitionIxCols("download_client_definition"));
        public global::SpacetimeDB.Table<DownloadClientStatus, DownloadClientStatusCols, DownloadClientStatusIxCols> DownloadClientStatus() => new("download_client_status", new DownloadClientStatusCols("download_client_status"), new DownloadClientStatusIxCols("download_client_status"));
        public global::SpacetimeDB.Table<DownloadHistory, DownloadHistoryCols, DownloadHistoryIxCols> DownloadHistory() => new("download_history", new DownloadHistoryCols("download_history"), new DownloadHistoryIxCols("download_history"));
        public global::SpacetimeDB.Table<Episode, EpisodeCols, EpisodeIxCols> Episode() => new("episode", new EpisodeCols("episode"), new EpisodeIxCols("episode"));
        public global::SpacetimeDB.Table<EpisodeFile, EpisodeFileCols, EpisodeFileIxCols> EpisodeFile() => new("episode_file", new EpisodeFileCols("episode_file"), new EpisodeFileIxCols("episode_file"));
        public global::SpacetimeDB.Table<EpisodeHistory, EpisodeHistoryCols, EpisodeHistoryIxCols> EpisodeHistory() => new("episode_history", new EpisodeHistoryCols("episode_history"), new EpisodeHistoryIxCols("episode_history"));
        public global::SpacetimeDB.Table<ImportListDefinition, ImportListDefinitionCols, ImportListDefinitionIxCols> ImportListDefinition() => new("import_list_definition", new ImportListDefinitionCols("import_list_definition"), new ImportListDefinitionIxCols("import_list_definition"));
        public global::SpacetimeDB.Table<ImportListExclusion, ImportListExclusionCols, ImportListExclusionIxCols> ImportListExclusion() => new("import_list_exclusion", new ImportListExclusionCols("import_list_exclusion"), new ImportListExclusionIxCols("import_list_exclusion"));
        public global::SpacetimeDB.Table<ImportListItem, ImportListItemCols, ImportListItemIxCols> ImportListItem() => new("import_list_item", new ImportListItemCols("import_list_item"), new ImportListItemIxCols("import_list_item"));
        public global::SpacetimeDB.Table<ImportListStatus, ImportListStatusCols, ImportListStatusIxCols> ImportListStatus() => new("import_list_status", new ImportListStatusCols("import_list_status"), new ImportListStatusIxCols("import_list_status"));
        public global::SpacetimeDB.Table<IndexerDefinition, IndexerDefinitionCols, IndexerDefinitionIxCols> IndexerDefinition() => new("indexer_definition", new IndexerDefinitionCols("indexer_definition"), new IndexerDefinitionIxCols("indexer_definition"));
        public global::SpacetimeDB.Table<IndexerStatus, IndexerStatusCols, IndexerStatusIxCols> IndexerStatus() => new("indexer_status", new IndexerStatusCols("indexer_status"), new IndexerStatusIxCols("indexer_status"));
        public global::SpacetimeDB.Table<MetadataDefinition, MetadataDefinitionCols, MetadataDefinitionIxCols> MetadataDefinition() => new("metadata_definition", new MetadataDefinitionCols("metadata_definition"), new MetadataDefinitionIxCols("metadata_definition"));
        public global::SpacetimeDB.Table<MetadataFile, MetadataFileCols, MetadataFileIxCols> MetadataFile() => new("metadata_file", new MetadataFileCols("metadata_file"), new MetadataFileIxCols("metadata_file"));
        public global::SpacetimeDB.Table<NamingConfig, NamingConfigCols, NamingConfigIxCols> NamingConfig() => new("naming_config", new NamingConfigCols("naming_config"), new NamingConfigIxCols("naming_config"));
        public global::SpacetimeDB.Table<NotificationDefinition, NotificationDefinitionCols, NotificationDefinitionIxCols> NotificationDefinition() => new("notification_definition", new NotificationDefinitionCols("notification_definition"), new NotificationDefinitionIxCols("notification_definition"));
        public global::SpacetimeDB.Table<NotificationStatus, NotificationStatusCols, NotificationStatusIxCols> NotificationStatus() => new("notification_status", new NotificationStatusCols("notification_status"), new NotificationStatusIxCols("notification_status"));
        public global::SpacetimeDB.Table<OtherExtraFile, OtherExtraFileCols, OtherExtraFileIxCols> OtherExtraFile() => new("other_extra_file", new OtherExtraFileCols("other_extra_file"), new OtherExtraFileIxCols("other_extra_file"));
        public global::SpacetimeDB.Table<PendingRelease, PendingReleaseCols, PendingReleaseIxCols> PendingRelease() => new("pending_release", new PendingReleaseCols("pending_release"), new PendingReleaseIxCols("pending_release"));
        public global::SpacetimeDB.Table<QualityDefinition, QualityDefinitionCols, QualityDefinitionIxCols> QualityDefinition() => new("quality_definition", new QualityDefinitionCols("quality_definition"), new QualityDefinitionIxCols("quality_definition"));
        public global::SpacetimeDB.Table<QualityProfile, QualityProfileCols, QualityProfileIxCols> QualityProfile() => new("quality_profile", new QualityProfileCols("quality_profile"), new QualityProfileIxCols("quality_profile"));
        public global::SpacetimeDB.Table<QualityProfileQualityRank, QualityProfileQualityRankCols, QualityProfileQualityRankIxCols> QualityProfileQualityRank() => new("quality_profile_quality_rank", new QualityProfileQualityRankCols("quality_profile_quality_rank"), new QualityProfileQualityRankIxCols("quality_profile_quality_rank"));
        public global::SpacetimeDB.Table<ReleaseProfile, ReleaseProfileCols, ReleaseProfileIxCols> ReleaseProfile() => new("release_profile", new ReleaseProfileCols("release_profile"), new ReleaseProfileIxCols("release_profile"));
        public global::SpacetimeDB.Table<RemotePathMapping, RemotePathMappingCols, RemotePathMappingIxCols> RemotePathMapping() => new("remote_path_mapping", new RemotePathMappingCols("remote_path_mapping"), new RemotePathMappingIxCols("remote_path_mapping"));
        public global::SpacetimeDB.Table<RootFolder, RootFolderCols, RootFolderIxCols> RootFolder() => new("root_folder", new RootFolderCols("root_folder"), new RootFolderIxCols("root_folder"));
        public global::SpacetimeDB.Table<SceneMapping, SceneMappingCols, SceneMappingIxCols> SceneMapping() => new("scene_mapping", new SceneMappingCols("scene_mapping"), new SceneMappingIxCols("scene_mapping"));
        public global::SpacetimeDB.Table<ScheduledTask, ScheduledTaskCols, ScheduledTaskIxCols> ScheduledTask() => new("scheduled_task", new ScheduledTaskCols("scheduled_task"), new ScheduledTaskIxCols("scheduled_task"));
        public global::SpacetimeDB.Table<Series, SeriesCols, SeriesIxCols> Series() => new("series", new SeriesCols("series"), new SeriesIxCols("series"));
        public global::SpacetimeDB.Table<SeriesTag, SeriesTagCols, SeriesTagIxCols> SeriesTag() => new("series_tag", new SeriesTagCols("series_tag"), new SeriesTagIxCols("series_tag"));
        public global::SpacetimeDB.Table<SubtitleFile, SubtitleFileCols, SubtitleFileIxCols> SubtitleFile() => new("subtitle_file", new SubtitleFileCols("subtitle_file"), new SubtitleFileIxCols("subtitle_file"));
        public global::SpacetimeDB.Table<Tag, TagCols, TagIxCols> Tag() => new("tag", new TagCols("tag"), new TagIxCols("tag"));
        public global::SpacetimeDB.Table<Config, TrustedConfigsCols, TrustedConfigsIxCols> TrustedConfigs() => new("trusted_configs", new TrustedConfigsCols("trusted_configs"), new TrustedConfigsIxCols("trusted_configs"));
        public global::SpacetimeDB.Table<TrustedConnection, TrustedConnectionCols, TrustedConnectionIxCols> TrustedConnection() => new("trusted_connection", new TrustedConnectionCols("trusted_connection"), new TrustedConnectionIxCols("trusted_connection"));
        public global::SpacetimeDB.Table<User, TrustedUsersCols, TrustedUsersIxCols> TrustedUsers() => new("trusted_users", new TrustedUsersCols("trusted_users"), new TrustedUsersIxCols("trusted_users"));
        public global::SpacetimeDB.Table<UpdateHistory, UpdateHistoryCols, UpdateHistoryIxCols> UpdateHistory() => new("update_history", new UpdateHistoryCols("update_history"), new UpdateHistoryIxCols("update_history"));
    }

    public sealed class TypedSubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private Action<SubscriptionEventContext>? Applied;
        private Action<ErrorContext, Exception>? Error;
        private readonly List<string> querySqls = new();

        internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
        {
            this.conn = conn;
            Applied = applied;
            Error = error;
        }

        public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
        {
            Applied += callback;
            return this;
        }

        public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
        {
            Error += callback;
            return this;
        }

        public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
        {
            var qb = new QueryBuilder();
            querySqls.Add(build(qb).ToSql());
            return this;
        }

        public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public abstract partial class Procedure
    {
        private Procedure() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
        new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch {
                Reducer.ClearModuleAuth args => Reducers.InvokeClearModuleAuth(eventContext, args),
                Reducer.ConfigureModuleAuth args => Reducers.InvokeConfigureModuleAuth(eventContext, args),
                Reducer.DeleteAutoTag args => Reducers.InvokeDeleteAutoTag(eventContext, args),
                Reducer.DeleteBlocklist args => Reducers.InvokeDeleteBlocklist(eventContext, args),
                Reducer.DeleteCommand args => Reducers.InvokeDeleteCommand(eventContext, args),
                Reducer.DeleteConfig args => Reducers.InvokeDeleteConfig(eventContext, args),
                Reducer.DeleteCustomFilter args => Reducers.InvokeDeleteCustomFilter(eventContext, args),
                Reducer.DeleteCustomFormat args => Reducers.InvokeDeleteCustomFormat(eventContext, args),
                Reducer.DeleteDelayProfile args => Reducers.InvokeDeleteDelayProfile(eventContext, args),
                Reducer.DeleteDownloadClientDefinition args => Reducers.InvokeDeleteDownloadClientDefinition(eventContext, args),
                Reducer.DeleteDownloadClientStatus args => Reducers.InvokeDeleteDownloadClientStatus(eventContext, args),
                Reducer.DeleteDownloadHistory args => Reducers.InvokeDeleteDownloadHistory(eventContext, args),
                Reducer.DeleteEpisode args => Reducers.InvokeDeleteEpisode(eventContext, args),
                Reducer.DeleteEpisodeFile args => Reducers.InvokeDeleteEpisodeFile(eventContext, args),
                Reducer.DeleteEpisodeHistory args => Reducers.InvokeDeleteEpisodeHistory(eventContext, args),
                Reducer.DeleteImportListDefinition args => Reducers.InvokeDeleteImportListDefinition(eventContext, args),
                Reducer.DeleteImportListExclusion args => Reducers.InvokeDeleteImportListExclusion(eventContext, args),
                Reducer.DeleteImportListItem args => Reducers.InvokeDeleteImportListItem(eventContext, args),
                Reducer.DeleteImportListStatus args => Reducers.InvokeDeleteImportListStatus(eventContext, args),
                Reducer.DeleteIndexerDefinition args => Reducers.InvokeDeleteIndexerDefinition(eventContext, args),
                Reducer.DeleteIndexerStatus args => Reducers.InvokeDeleteIndexerStatus(eventContext, args),
                Reducer.DeleteMetadataDefinition args => Reducers.InvokeDeleteMetadataDefinition(eventContext, args),
                Reducer.DeleteMetadataFile args => Reducers.InvokeDeleteMetadataFile(eventContext, args),
                Reducer.DeleteNamingConfig args => Reducers.InvokeDeleteNamingConfig(eventContext, args),
                Reducer.DeleteNotificationDefinition args => Reducers.InvokeDeleteNotificationDefinition(eventContext, args),
                Reducer.DeleteNotificationStatus args => Reducers.InvokeDeleteNotificationStatus(eventContext, args),
                Reducer.DeleteOtherExtraFile args => Reducers.InvokeDeleteOtherExtraFile(eventContext, args),
                Reducer.DeletePendingRelease args => Reducers.InvokeDeletePendingRelease(eventContext, args),
                Reducer.DeleteQualityDefinition args => Reducers.InvokeDeleteQualityDefinition(eventContext, args),
                Reducer.DeleteQualityProfile args => Reducers.InvokeDeleteQualityProfile(eventContext, args),
                Reducer.DeleteQualityProfileQualityRank args => Reducers.InvokeDeleteQualityProfileQualityRank(eventContext, args),
                Reducer.DeleteReleaseProfile args => Reducers.InvokeDeleteReleaseProfile(eventContext, args),
                Reducer.DeleteRemotePathMapping args => Reducers.InvokeDeleteRemotePathMapping(eventContext, args),
                Reducer.DeleteRootFolder args => Reducers.InvokeDeleteRootFolder(eventContext, args),
                Reducer.DeleteSceneMapping args => Reducers.InvokeDeleteSceneMapping(eventContext, args),
                Reducer.DeleteScheduledTask args => Reducers.InvokeDeleteScheduledTask(eventContext, args),
                Reducer.DeleteSeries args => Reducers.InvokeDeleteSeries(eventContext, args),
                Reducer.DeleteSubtitleFile args => Reducers.InvokeDeleteSubtitleFile(eventContext, args),
                Reducer.DeleteTag args => Reducers.InvokeDeleteTag(eventContext, args),
                Reducer.DeleteUpdateHistory args => Reducers.InvokeDeleteUpdateHistory(eventContext, args),
                Reducer.DeleteUser args => Reducers.InvokeDeleteUser(eventContext, args),
                Reducer.InsertAutoTag args => Reducers.InvokeInsertAutoTag(eventContext, args),
                Reducer.InsertBlocklist args => Reducers.InvokeInsertBlocklist(eventContext, args),
                Reducer.InsertCommand args => Reducers.InvokeInsertCommand(eventContext, args),
                Reducer.InsertConfig args => Reducers.InvokeInsertConfig(eventContext, args),
                Reducer.InsertCustomFilter args => Reducers.InvokeInsertCustomFilter(eventContext, args),
                Reducer.InsertCustomFormat args => Reducers.InvokeInsertCustomFormat(eventContext, args),
                Reducer.InsertDelayProfile args => Reducers.InvokeInsertDelayProfile(eventContext, args),
                Reducer.InsertDownloadClientDefinition args => Reducers.InvokeInsertDownloadClientDefinition(eventContext, args),
                Reducer.InsertDownloadClientStatus args => Reducers.InvokeInsertDownloadClientStatus(eventContext, args),
                Reducer.InsertDownloadHistory args => Reducers.InvokeInsertDownloadHistory(eventContext, args),
                Reducer.InsertEpisode args => Reducers.InvokeInsertEpisode(eventContext, args),
                Reducer.InsertEpisodeFile args => Reducers.InvokeInsertEpisodeFile(eventContext, args),
                Reducer.InsertEpisodeHistory args => Reducers.InvokeInsertEpisodeHistory(eventContext, args),
                Reducer.InsertImportListDefinition args => Reducers.InvokeInsertImportListDefinition(eventContext, args),
                Reducer.InsertImportListExclusion args => Reducers.InvokeInsertImportListExclusion(eventContext, args),
                Reducer.InsertImportListItem args => Reducers.InvokeInsertImportListItem(eventContext, args),
                Reducer.InsertImportListStatus args => Reducers.InvokeInsertImportListStatus(eventContext, args),
                Reducer.InsertIndexerDefinition args => Reducers.InvokeInsertIndexerDefinition(eventContext, args),
                Reducer.InsertIndexerStatus args => Reducers.InvokeInsertIndexerStatus(eventContext, args),
                Reducer.InsertMetadataDefinition args => Reducers.InvokeInsertMetadataDefinition(eventContext, args),
                Reducer.InsertMetadataFile args => Reducers.InvokeInsertMetadataFile(eventContext, args),
                Reducer.InsertNamingConfig args => Reducers.InvokeInsertNamingConfig(eventContext, args),
                Reducer.InsertNotificationDefinition args => Reducers.InvokeInsertNotificationDefinition(eventContext, args),
                Reducer.InsertNotificationStatus args => Reducers.InvokeInsertNotificationStatus(eventContext, args),
                Reducer.InsertOtherExtraFile args => Reducers.InvokeInsertOtherExtraFile(eventContext, args),
                Reducer.InsertPendingRelease args => Reducers.InvokeInsertPendingRelease(eventContext, args),
                Reducer.InsertQualityDefinition args => Reducers.InvokeInsertQualityDefinition(eventContext, args),
                Reducer.InsertQualityProfile args => Reducers.InvokeInsertQualityProfile(eventContext, args),
                Reducer.InsertQualityProfileQualityRank args => Reducers.InvokeInsertQualityProfileQualityRank(eventContext, args),
                Reducer.InsertReleaseProfile args => Reducers.InvokeInsertReleaseProfile(eventContext, args),
                Reducer.InsertRemotePathMapping args => Reducers.InvokeInsertRemotePathMapping(eventContext, args),
                Reducer.InsertRootFolder args => Reducers.InvokeInsertRootFolder(eventContext, args),
                Reducer.InsertSceneMapping args => Reducers.InvokeInsertSceneMapping(eventContext, args),
                Reducer.InsertScheduledTask args => Reducers.InvokeInsertScheduledTask(eventContext, args),
                Reducer.InsertSeries args => Reducers.InvokeInsertSeries(eventContext, args),
                Reducer.InsertSubtitleFile args => Reducers.InvokeInsertSubtitleFile(eventContext, args),
                Reducer.InsertTag args => Reducers.InvokeInsertTag(eventContext, args),
                Reducer.InsertUpdateHistory args => Reducers.InvokeInsertUpdateHistory(eventContext, args),
                Reducer.InsertUser args => Reducers.InvokeInsertUser(eventContext, args),
                Reducer.MigrateInsertAutoTag args => Reducers.InvokeMigrateInsertAutoTag(eventContext, args),
                Reducer.MigrateInsertBlocklist args => Reducers.InvokeMigrateInsertBlocklist(eventContext, args),
                Reducer.MigrateInsertConfig args => Reducers.InvokeMigrateInsertConfig(eventContext, args),
                Reducer.MigrateInsertCustomFilter args => Reducers.InvokeMigrateInsertCustomFilter(eventContext, args),
                Reducer.MigrateInsertCustomFormat args => Reducers.InvokeMigrateInsertCustomFormat(eventContext, args),
                Reducer.MigrateInsertDelayProfile args => Reducers.InvokeMigrateInsertDelayProfile(eventContext, args),
                Reducer.MigrateInsertDownloadClientDefinition args => Reducers.InvokeMigrateInsertDownloadClientDefinition(eventContext, args),
                Reducer.MigrateInsertDownloadHistory args => Reducers.InvokeMigrateInsertDownloadHistory(eventContext, args),
                Reducer.MigrateInsertEpisode args => Reducers.InvokeMigrateInsertEpisode(eventContext, args),
                Reducer.MigrateInsertEpisodeFile args => Reducers.InvokeMigrateInsertEpisodeFile(eventContext, args),
                Reducer.MigrateInsertEpisodeHistory args => Reducers.InvokeMigrateInsertEpisodeHistory(eventContext, args),
                Reducer.MigrateInsertImportListDefinition args => Reducers.InvokeMigrateInsertImportListDefinition(eventContext, args),
                Reducer.MigrateInsertImportListExclusion args => Reducers.InvokeMigrateInsertImportListExclusion(eventContext, args),
                Reducer.MigrateInsertIndexerDefinition args => Reducers.InvokeMigrateInsertIndexerDefinition(eventContext, args),
                Reducer.MigrateInsertMetadataDefinition args => Reducers.InvokeMigrateInsertMetadataDefinition(eventContext, args),
                Reducer.MigrateInsertMetadataFile args => Reducers.InvokeMigrateInsertMetadataFile(eventContext, args),
                Reducer.MigrateInsertNamingConfig args => Reducers.InvokeMigrateInsertNamingConfig(eventContext, args),
                Reducer.MigrateInsertNotificationDefinition args => Reducers.InvokeMigrateInsertNotificationDefinition(eventContext, args),
                Reducer.MigrateInsertOtherExtraFile args => Reducers.InvokeMigrateInsertOtherExtraFile(eventContext, args),
                Reducer.MigrateInsertPendingRelease args => Reducers.InvokeMigrateInsertPendingRelease(eventContext, args),
                Reducer.MigrateInsertQualityDefinition args => Reducers.InvokeMigrateInsertQualityDefinition(eventContext, args),
                Reducer.MigrateInsertQualityProfile args => Reducers.InvokeMigrateInsertQualityProfile(eventContext, args),
                Reducer.MigrateInsertReleaseProfile args => Reducers.InvokeMigrateInsertReleaseProfile(eventContext, args),
                Reducer.MigrateInsertRemotePathMapping args => Reducers.InvokeMigrateInsertRemotePathMapping(eventContext, args),
                Reducer.MigrateInsertRootFolder args => Reducers.InvokeMigrateInsertRootFolder(eventContext, args),
                Reducer.MigrateInsertScheduledTask args => Reducers.InvokeMigrateInsertScheduledTask(eventContext, args),
                Reducer.MigrateInsertSeries args => Reducers.InvokeMigrateInsertSeries(eventContext, args),
                Reducer.MigrateInsertSubtitleFile args => Reducers.InvokeMigrateInsertSubtitleFile(eventContext, args),
                Reducer.MigrateInsertTag args => Reducers.InvokeMigrateInsertTag(eventContext, args),
                Reducer.MigrateInsertUpdateHistory args => Reducers.InvokeMigrateInsertUpdateHistory(eventContext, args),
                Reducer.MigrateInsertUser args => Reducers.InvokeMigrateInsertUser(eventContext, args),
                Reducer.OrphanStartedCommands args => Reducers.InvokeOrphanStartedCommands(eventContext, args),
                Reducer.ReplaceQualityProfileQualityRanks args => Reducers.InvokeReplaceQualityProfileQualityRanks(eventContext, args),
                Reducer.ReplaceSeriesTags args => Reducers.InvokeReplaceSeriesTags(eventContext, args),
                Reducer.UpdateAutoTag args => Reducers.InvokeUpdateAutoTag(eventContext, args),
                Reducer.UpdateBlocklist args => Reducers.InvokeUpdateBlocklist(eventContext, args),
                Reducer.UpdateCommand args => Reducers.InvokeUpdateCommand(eventContext, args),
                Reducer.UpdateConfig args => Reducers.InvokeUpdateConfig(eventContext, args),
                Reducer.UpdateCustomFilter args => Reducers.InvokeUpdateCustomFilter(eventContext, args),
                Reducer.UpdateCustomFormat args => Reducers.InvokeUpdateCustomFormat(eventContext, args),
                Reducer.UpdateDelayProfile args => Reducers.InvokeUpdateDelayProfile(eventContext, args),
                Reducer.UpdateDownloadClientDefinition args => Reducers.InvokeUpdateDownloadClientDefinition(eventContext, args),
                Reducer.UpdateDownloadClientStatus args => Reducers.InvokeUpdateDownloadClientStatus(eventContext, args),
                Reducer.UpdateDownloadHistory args => Reducers.InvokeUpdateDownloadHistory(eventContext, args),
                Reducer.UpdateEpisode args => Reducers.InvokeUpdateEpisode(eventContext, args),
                Reducer.UpdateEpisodeFile args => Reducers.InvokeUpdateEpisodeFile(eventContext, args),
                Reducer.UpdateEpisodeHistory args => Reducers.InvokeUpdateEpisodeHistory(eventContext, args),
                Reducer.UpdateImportListDefinition args => Reducers.InvokeUpdateImportListDefinition(eventContext, args),
                Reducer.UpdateImportListExclusion args => Reducers.InvokeUpdateImportListExclusion(eventContext, args),
                Reducer.UpdateImportListItem args => Reducers.InvokeUpdateImportListItem(eventContext, args),
                Reducer.UpdateImportListStatus args => Reducers.InvokeUpdateImportListStatus(eventContext, args),
                Reducer.UpdateIndexerDefinition args => Reducers.InvokeUpdateIndexerDefinition(eventContext, args),
                Reducer.UpdateIndexerStatus args => Reducers.InvokeUpdateIndexerStatus(eventContext, args),
                Reducer.UpdateMetadataDefinition args => Reducers.InvokeUpdateMetadataDefinition(eventContext, args),
                Reducer.UpdateMetadataFile args => Reducers.InvokeUpdateMetadataFile(eventContext, args),
                Reducer.UpdateNamingConfig args => Reducers.InvokeUpdateNamingConfig(eventContext, args),
                Reducer.UpdateNotificationDefinition args => Reducers.InvokeUpdateNotificationDefinition(eventContext, args),
                Reducer.UpdateNotificationStatus args => Reducers.InvokeUpdateNotificationStatus(eventContext, args),
                Reducer.UpdateOtherExtraFile args => Reducers.InvokeUpdateOtherExtraFile(eventContext, args),
                Reducer.UpdatePendingRelease args => Reducers.InvokeUpdatePendingRelease(eventContext, args),
                Reducer.UpdateQualityDefinition args => Reducers.InvokeUpdateQualityDefinition(eventContext, args),
                Reducer.UpdateQualityProfile args => Reducers.InvokeUpdateQualityProfile(eventContext, args),
                Reducer.UpdateQualityProfileQualityRank args => Reducers.InvokeUpdateQualityProfileQualityRank(eventContext, args),
                Reducer.UpdateReleaseProfile args => Reducers.InvokeUpdateReleaseProfile(eventContext, args),
                Reducer.UpdateRemotePathMapping args => Reducers.InvokeUpdateRemotePathMapping(eventContext, args),
                Reducer.UpdateRootFolder args => Reducers.InvokeUpdateRootFolder(eventContext, args),
                Reducer.UpdateSceneMapping args => Reducers.InvokeUpdateSceneMapping(eventContext, args),
                Reducer.UpdateScheduledTask args => Reducers.InvokeUpdateScheduledTask(eventContext, args),
                Reducer.UpdateSeries args => Reducers.InvokeUpdateSeries(eventContext, args),
                Reducer.UpdateSubtitleFile args => Reducers.InvokeUpdateSubtitleFile(eventContext, args),
                Reducer.UpdateTag args => Reducers.InvokeUpdateTag(eventContext, args),
                Reducer.UpdateUpdateHistory args => Reducers.InvokeUpdateUpdateHistory(eventContext, args),
                Reducer.UpdateUser args => Reducers.InvokeUpdateUser(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
